scripts/import_allspawns.sh

krzthehunter writing too fast n furious

bugfix for import_allspawn.sh

---

README.md
configs/config.ini.example

added information about the phone setup and several little improvements.

Just another README.md update :)

---

scripts/import_allspawns.sh

rocketmap was kinda fubar, now i have duke's DB and testing is FAR FAR easier. this should work.
I recommend all rm users who already imported run this new version again, but deleting trs_spawn first is now optional, not necessary.

big time fixes to importer

---

madmin/templates/map.html

Added gym images to gyms in Madmin

---

db/monocleWrapper.py

Stop them getting through and breaking sorting when going into JSON

Stop NULL external_id & IFNULL sponsor & team

---

db/monocleWrapper.py

**#MAD Control Scan Script**
Start, Stop and Status exemples:
**./scan.bash start 
./scan.bash stop 
./scan.bash status**

MAD Control Scan Script

---

utils/walkerArgs.py

Needed to remove action='store_true'.
But look at the changed line^^

fixed ocr_thread_count, now accepting ints

---

db/monocleWrapper.py

Add missing select of quest task from monoclewrapper

Add missing select of quest task from monoclewrapper

---

utils/webhookHelper.py

hopefully fix egg webhooks for PA support

---

db/monocleWrapper.py
db/rmWrapper.py
utils/webhookHelper.py

This needs testing.  Don't merge before at least two people confirmed this doesn't break webhooks for RM nor for Monocle.

add last_modified to gym webhook

---

madmin/madmin.py
madmin/templates/map.html

set center of map to config values

---

websocket/WebsocketServer.py

makes websocket logging way less noisy if running in verbose mode and overal

Make the log level for websocket library INFO

---

scripts/intelimport.sh

Fixed for RM (removed cat, wrong formatting + regex)
**Not tested for Monocle!**
_Make it working with support by @krzee_

fix RM intelimport

---

route/RouteManagerBase.py

Noticed error in console/code.
Config vs Configs.
Quick fix.

RouteManagerBase.py fix

---

requirements.txt
requirements_ocr.txt

Updated numpy to 1.16.0 to make it buildable on a pi.

Can build on a pi and check that it works on win 10 too

---

utils/version.py

Seems like there was a copy-paste error - migration will not succeed as it is off by one.

Bugfix - Update version.py with correct version check number

---

madmin/templates/map.html

Make madmin map list out the right text for research tasks

---

db/monocleWrapper.py
db/rmWrapper.py
utils/webhookHelper.py

rebase #84 thx to PixelBurstHD

Update webhook to send weather/gender

---

madmin/static/vars/vars_parser.json

After initial setup I found that if I needed to change something it was mostly in Devices section - it was kinda annoying to scroll past all the configured Areas to get to Devices. Devices first, Areas second, Auth last.

Switch section Devices with Areas.

---

madmin/static/vars/settings.json

Update settings.json, remove max_data_err_counter

---

madmin/templates/quests.html

Small QOL change for big boys with lots of quests and no time for paging

Allow the user to show all quests at once with the "All" selection

---

db/monocleWrapper.py

Confirmation from Discord that it's working now. #149

Fix not updating gyms on mono

---

madmin/madmin.py
madmin/static/vars/settings.json
madmin/static/vars/vars_parser.json
madmin/templates/base.html
madmin/templates/change_gym.html
madmin/templates/change_mon.html
madmin/templates/change_raid.html
madmin/templates/gyms.html
madmin/templates/index.html
madmin/templates/map.html
madmin/templates/match_unknown.html
madmin/templates/parser.html
madmin/templates/quests.html
madmin/templates/raids.html
madmin/templates/screens.html
madmin/templates/sel_type.html
madmin/templates/settings.html
madmin/templates/statistics.html
madmin/templates/status.html
madmin/templates/unknown.html

Changes:
* Cleaned up and formatted code
* **Fixed wrong request args** access (replace error introduced with basic auth)
* Rewrote some functions that had redundant or even unused code
* **Made all links relative** to use MADmin also on subpath (e.g. with use of a reverse proxy)
* Fixed small display issue with map
_Please test! I didn't due to slightly different code base._

Fix bugs and clean up MADmin + Make all links relative

---

route/RouteManagerBase.py

bugfix to allow time spent each round to be calculated correctly

Update started time only when it wasn't already set

---

configmode.py
configs/mappings_example.json
madmin/madmin.py
madmin/static/vars/settings.json
madmin/static/vars/vars_parser.json
madmin/templates/settings.html
start.py
utils/logging.py
utils/mappingParser.py

Adding configuration pools for devices. So one config could assign to X devices. Special parameters on devices overwrites global parameters.

Settingpool

---

madmin/madmin.py

added the correct conf_args to obtain new file_path arg to display Workers and Routes in Map View

Fix MADmin Map View

---

utils/s2Helper.py
webhook/webhookworker.py

Send the coords of the s2Cell to the webhook. This allows notifications showing the boundary of the cell and is in keeping with the old payload.

Weather coords

---

utils/s2Helper.py
webhook/webhookworker.py

Revert "Weather coords"

---

README.md

Add link to wiki so more people will find it

---

db/monocleWrapper.py

Compared RM and adapted the change, tested on my instance

Fix Spawn Statistics Monocle

---

madmin/templates/index.html

Too lazy to click that hamburger menu on mobile.

Update index.html add Phonecontrol to links

---

webhook/webhookworker.py

Add conditions for research about catching specific pokemen

Bugfix for poracle quest support

---

madmin/templates/statistics.html

adjust wording

---

db/monocleWrapper.py

Fix copy-pasterinos, because I was like "WTF?" when checking logs

Fix typo in logs, this is not rm

---

madmin/templates/parser.html

Most of those can't be empty for proper usage, MAD won't work with empty values.

Fix walkervalue validation in madmin

---

worker/WorkerQuests.py

Fix missing coords in logs

---

madmin/routes/config.py

Fix missing requirements for mon-picker.

---

utils/mappingParser.py

We don't really need that 400 there.

Fix misleading log info

---

utils/version.py

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '')' at line 1

Add missing quote to version.py

---

worker/WorkerQuests.py

"Œ"  is reconignize  "CE"
See log for confirmation 
[  WorkerQuests][    INFO] Found item text: CEuf Chance

Fix text for Lucky Eggs ( French)

---

websocket/communicator.py

Update communicator.py remove mediaprojection message

---

utils/adb.py

One line, as always. Changing from error to warning and providing some more info for ignoring it.

Update adb.py for more info in log

---

madmin/templates/map.html

fix for the error that showing up when opening the popup of a mon without IV (in MADmin)
Mons now without IV are getting this popup without all the IV scan stuff:

fix error showing up when opening mon without IV

---

websocket/WebsocketServer.py

It will be easier to figure out which walker needs adjustments

Update WebsocketServer.py log device name when out of walkers

---

README.md

Everything from the README is in our wiki now, so lets link to it :)

Add the wiki to the README

---

configmode.py
utils/MappingManager.py

> RuntimeError: geofence_included for area 'huehuedurr' is specified but file does not exist ('/home/mad2/MAD/configs/geofences/ND_raid.txt').
Like that :)

Log full path to missing geofence files

---

configs/config.ini.example

The auto_hatch is not used anymore too, but there are still functions for that in code... so leaving it there, maybe it will be back in future :)

cleanup of config.ini of non-existing params, some wording changes

---

locale/en/pokemon.json

removed "Alolan" from 3 Pokemon.

changes to pokemon.json

---

websocket/WebsocketServer.py

Why only I had that problem 🥇?! Sorry Grenn for wasting time on other version of RGC, we should've -vvvvvv from the beginning.

Set max number of elements to split, so XML with ; won't be cut.

---

configs/config.ini.example

added "quest" to possible types of webhook_url prefixes

added "quest" to possible types

---

madmin/static/vars/vars_parser.json

So people won't ask "Where do I put my Google password" or something. I hope.

Fix typo and add some clarification 

---

geofence/geofenceHelper.py

Accept geofence files with no [area] header on the first line

Don't get a booboo if geofence file has no [name]

---

db/rmWrapper.py
madmin/routes/statistics.py

Works for me, someone with rm test it more please.

cast to bigint, fix stats a little - distinct and make the avg really avg

---

db/rmWrapper.py

Extend the UPDATE clause of the gym details to allow updating the image
url for already existing gyms when an image url is present

Allow updates of gym image urls

---

db/monocleWrapper.py
webhook/webhookworker.py

Obviously awaiting outputs of PA for the final design.

Add Monocle webhook sending for TR invasion

---

db/dbWrapperBase.py
db/monocleWrapper.py
db/rmWrapper.py
mitm_receiver/MITMDataProcessor.py

This makes it possible to open a gym and automatically populate the
details (name, url, and description) of the gym in the DB.

Handle protocol type 156 to update gym details

---

worker/WorkerQuests.py

and rewrite logs, so we can easier spot what and when went wrong

Not increase quest count for clearing when cooldown and no quest

---

configs/config.ini.example

Update config.ini.example, mention Team Rocket

---

db/rmWrapper.py

This is only left, it must be this, right? @cecpk

Maybe FIX: replace error v2

---

ocr/screenPath.py

Probably totally not needed, but hey :)

Stop leaking GGL/PTC addresses into logs.

---

websocket/WebsocketServer.py

I am pretty sure you wanted double underscore :)

Fix has no attribute '_mapping_manager'

---

scripts/databasesetup.py

add shebang to databasesetup.py

---

madmin/routes/config.py

Areas, devices, walkers, auth and global mon list

sort mappings entries alphabetically in madmin view

---

locale/de/LC_MESSAGES/quest.po
locale/fr/LC_MESSAGES/quest.po
utils/questGen.py

Task text for spining new pokestops updated to reflect what's actually used in game

Correct wording on Research task

---

webhook/webhookworker.py

grunt_type code was duplicated

remove duplicate grunt_type in webhook code

---

configs/mappings_example.json

We should use name, not the whole key. bbdoc @ discord :D

Update mappings_example.json, fix typo

---

madmin/routes/config.py

Fix edge case in mon id picker for just one mon

---

utils/MappingManager.py

again. I guess it got lost in some master-dev sync.

Remove misleading log

---

worker/WorkerQuests.py

when we don't need to wait before spinnig - tell it more clearly in the log

Use better English

---

db/rmWrapper.py
madmin/routes/statistics.py
madmin/templates/statistics/mon_statistics.html

order shiny by time_scan, simplify data view.
Looks like this: https://i.imgur.com/j0Z4jk1.png [ignore images missing]

Shiny stats display simplified

---

worker/MITMBase.py
worker/WorkerBase.py
worker/WorkerQuests.py

Moving some stuff from error to warning/info - Like "Box is full", "Not on main screen" or "Scanned X location, restarting".

Various useless log fixes

---

db/dbWrapperBase.py

easier to pinpoint where something is wrong

also log broken query, not only error message

---

configs/config.ini.example
db/rmWrapper.py
utils/walkerArgs.py

This is useful for events with extended lures.

Add option to change lure duration

---

Dockerfile

Enables automatic builds for the dev branch via dockerhub.

Update Dockerfile on Dev

---

utils/logging.py

For example: start.py --log_level ERROR

and tuple here too - if anyone uses it via label

---

madmin/static/js/madmin.js

Map wouldn't appear with this error

Fix broken madmin JS

---

scripts/migrate_to_rocketmap.sh

Missing -u option in order to indeed use root user for DB and Schema creation...

Connect as root for creating DB and schema

---

madmin/routes/config.py

Last OCR cleaning went little too far ;-)

Fix missing return

---

locale/en/types.json
locale/quest.pot
utils/questGen.py

Adds new quest types like grunt battles and take snapshots that are going to be used in Water Festival
PS - missing DE and FR translations
NEEDS TESTING

Add new quest types to the quest parser and EN languages

---

madmin/static/vars/vars_parser.json

Should be more clear now, I hope.

Wording on PTC, parentheses was a problem

---

utils/authHelper.py

Removed string manipulation from the authentication code and better handling of character bytes

Cleanup of the authentication code

---

madmin/routes/map.py

Save lat, lon not lat, lat.
On top of that please also merge #346 
Confirmed working with those changes :)

Fix madmin geofence editor lat,lat

---

madmin/routes/control.py
madmin/templates/phonescreens.html

Same button like last time, just more options after click.
Copy-paste of ajax calls, probably should be moved to dedicated method soon.
Not sure if ADB part works - can't test. It should, in theory.

Restart POGO from madmin phonecontrol

---

worker/WorkerBase.py

detect same screens while screendetection

check for pogo freeze

---

scripts/intelimport.sh

I swear i tested my PR on my server!!1 🙈

fix intelimport.sh

---

scripts/databasesetup.py

+ a fix for a wierd IndentationError. Wondering how it got here 🤔

adjust databasesetup.py for RM only

---

route/RouteManagerQuests.py

I guess it should be like that :)

Missing param for generating route

---

madmin/routes/control.py

Sort (non adb) devices by their names in phonecontrol

Sort devices by name

---

worker/WorkerBase.py

#399 caused `IndentationError: unexpected indent`
This PR will solve this error.

Fix indent errors

---

madmin/routes/statistics.py

@auth_required for stats

---

route/RouteManagerBase.py

remove "Round of" from the log line about moving to prio events

Improve wording of priority queue logging

---

db/dbWrapperBase.py

This line has no effect so can be removed.

Remove unnecessary line.

---

madmin/templates/settings_singlearea.html
utils/data_manager.py

Mon List dependency fix
Mon List will be available regardless of advanced_config option

Madmin rework

---

madmin/api/modules/ftr_area.py
madmin/routes/config.py
madmin/templates/settings_singlearea.html

Geofence is now a picker.  The picker is also sorted

Geofence feature parity

---

madmin/routes/statistics.py
madmin/templates/status.html

Updated the status page to handle areas that no longer exist

Updated the status page to handle areas that no longer exist

---

madmin/api/modules/ftr_area.py
madmin/api/modules/ftr_devicesetting.py
madmin/api/modules/ftr_monlist.py
madmin/api/modules/ftr_walkerarea.py
madmin/templates/settings_walkerarea.html
scripts/doc_field_generator.py

Fix for idle geofence and walkermax not working with '0'.

Madmin rework fixes

---

madmin/templates/statistics/mon_statistics.html
madmin/templates/statistics/shiny_statistics.html
madmin/templates/statistics/spawn_statistics.html
madmin/templates/statistics/statistics.html

Link found by cec, forwared by krzTrack https://github.com/JohnTendik/jtrt-tables/issues/34
One line PR by me, like always! ;-)
I totally on purpose put it in one/same line -  so when copy-pasting in future we will remember that this thing is useful and (kinda) needed. If that triggers anyone I can redo for new line.

Make ordering works from first load of webpage.

---

madmin/api/modules/ftr_walkerarea.py

Allow walkervalue empty to be an empty string

---

madmin/templates/phonescreens.html

Put reboot dialog above block/loading screen

---

madmin/static/js/madmin.js

Display IV0 on madmin

---

madmin/api/apiHandler.py
madmin/api/apiRequest.py
madmin/api/modules/ftr_walker.py

Handles invalid JSON when posting + PUT has same requirements as POST

Api issues

---

configs/config.ini.example
madmin/api/modules/ftr_device.py
madmin/api/modules/ftr_devicesetting.py
madmin/functions.py
madmin/routes/control.py
madmin/static/vars/template/phone.tpl
madmin/templates/base.html
madmin/templates/settings_areas.html
madmin/templates/settings_walkerarea.html
utils/updater.py
utils/walkerArgs.py
worker/MITMBase.py
worker/WorkerBase.py

retry of #311 
Phone isn't the right name anymore :D I also changed some loglines, so its not only MADmin

Rename Phonecontrol to Devicecontrol

---

madmin/api/modules/ftr_device.py

Looks like it got lost with new rework. Please double-check if that is all it's needed - I am not sure how this new madmin magic works :)

Add injection_thresh_reboot to device settings

---

madmin/api/apiException.py
madmin/api/apiHandler.py
madmin/api/modules/ftr_area.py
tests/api/api_base.py
utils/data_manager.py

Cleaned up the ResourceHandler to push mode handling into ftr_area

Area mode cleanup

---

madmin/api/apiHandler.py
madmin/api/apiRequest.py
madmin/api/apiResponse.py
madmin/static/js/madmin_settings.js
madmin/templates/settings_singlearea.html
madmin/templates/settings_singleauth.html
madmin/templates/settings_singledevice.html
madmin/templates/settings_singleivlist.html
madmin/templates/settings_singlesharedsetting.html
madmin/templates/settings_singlewalker.html
madmin/templates/settings_walkerarea.html
tests/api/test_area.py

Fixes #495 by always processing all values received by the API.  The UI has been updated to only send fields that have changed in the current iteration

API now processes empty values correctly

---

scripts/remove_all_spawns_within_geofence.py

Remove all spawnpoints within geofence. Real geofence, not just square bbox.
usage `python3 remove_all_spawns_within_geofence.py GEOFENCEFILENAME`
It will append ".txt" and if there is no "/" in geofencefilename it will append standard MAD path.
> $ python3 remove_all_spawns_within_geofence.py test1.txt
> [11-01 23:28:34.63] [       MainThread] [            logging:70  ] [    INFO] Setting log level to 9 (DEBUG2).
> [11-01 23:28:34.64] [       MainThread] [               test:53  ] [    INFO] Trying to use file: ../configs/geofences/test1.txt
> [11-01 23:28:34.64] [       MainThread] [               test:55  ] [   ERROR] Geofence file ../configs/geofences/test1.txt not found, exit
> $ python3 remove_all_spawns_within_geofence.py test1
> [11-01 23:28:41.42] [       MainThread] [ …

Script to remove ALL spawnpoints within MAD geofence

---

madmin/templates/base.html

One little Phonecontrol made it into master somehow.

Actually renaming Phonecontrol (lol)

---

worker/WorkerBase.py
worker/WorkerMITM.py
worker/WorkerQuests.py

There seems to be no need for an abstract method and 2 implementations which
do the very same.

Pull up WorkerBase._start_pogo

---

madmin/templates/quests.html

Add missing url_for for area selection on quest page

---

db/rmWrapper.py

Allows us to show  team rocket leader info on pokestops

Save team go rocket leader info if it's there

---

madmin/templates/quests.html

quest_pub page now displays without auth (if enabled in config)

---

madmin/api/modules/ftr_devicesetting.py

This thing should never be here

Delete routecalc method from devicesettings

---

madmin/static/js/madmin.js

This fixes a small issue caused by #567.
More info:

Fix last mon seen.

---

worker/WorkerBase.py

Fix for #597

---

db/DbSchemaUpdater.py
db/DbWrapper.py
db/PooledQueryExecutor.py
madmin/routes/statistics.py
utils/version.py
worker/MITMBase.py
worker/WorkerBase.py
worker/WorkerConfigmode.py

trs_status.instance is being removed and converted to trs_status.instance_id to avoid collation errors across tables

Updated trs_status.instance to int

---

route/RouteManagerBase.py
route/RouteManagerIV.py
route/RouteManagerMon.py
route/RouteManagerQuests.py
route/RouteManagerRaids.py
utils/data_manager/modules/routecalc.py

Quest routes were not being regenerated to pickup new stops

QuestRoute Fix

---

configmode.py
madmin/api/__init__.py
madmin/api/apiHandler.py
madmin/api/modules/ftr_device.py
madmin/madmin.py
madmin/templates/settings_areas.html
madmin/templates/settings_devices.html
route/RouteManagerBase.py
start.py
utils/MappingManager.py
utils/data_manager/__init__.py
utils/data_manager/dm_exceptions.py
utils/data_manager/modules/device.py
websocket/WebsocketServer.py
worker/WorkerBase.py

An API RPC function has been implemented that allows pausing and un-pausing of workers.  The UI has been updated to include this functionality on the devices page.
This implementation is in regards to #589

Pause / Unpause workers

---

configs/config.ini.example
utils/updater.py
utils/walkerArgs.py

Start more than one job the same time.
Use config.ini argument job_thread_count to set the thread amount (Default:2)

Multi thread job processing

---

madmin/routes/config.py
madmin/templates/settings_areas.html
madmin/templates/settings_singleroutecalc.html
tests/api/test_routecalc.py
utils/data_manager/modules/routecalc.py

Implementation for #618 .  Routecalcs are now editable in MADmin.  They are accessible on the area page on the route icon

Routecalc in MADmin

---

start.py

Extra info what to do if checking dependencies failed.

Verbose info about how-to update packages.

---

start.py

Fix for #622 
-or will successfully recalculate the route then stop MAD

Fix: Config Option '-or' works with quick recalc

---

db/DbPogoProtoSubmit.py
db/DbSchemaUpdater.py
db/DbWrapper.py
madmin/static/js/madmin.js
madmin/templates/quests.html
utils/questGen.py
webhook/webhookworker.py

Quest reward pokemon will now save form and costume to DB as new columns
Webhooks are also ammended with both these fields, should they be set in the protos

Quest reward forms and costumes in DB

---

start.py
tests/api/api_base.py
utils/local_api.py

Unit tests now run after the API is available vs a delay (which may not be sufficient).  Added extra debug around the shutdown steps.

Unit-Test tweaks

---

db/DbWrapper.py
madmin/routes/map.py
madmin/static/js/madmin.js

Manually updated the database to show a single pokestop with a quest

pokestops without quests now appear red on the map

---

madmin/templates/phonescreens.html

This is for cec and other plebs using lower resolution displays.

device control: always center screens and use a bit more width

---

mapadroid/route/RouteManagerBase.py
mapadroid/utils/data_manager/modules/routecalc.py

Recalcing a route now correctly updated last_updated

---

mapadroid/utils/apk_util.py
mapadroid/utils/updater.py

Fix for smart update processing

---

locale/de/quest_templates.json
locale/en/quest_templates.json
locale/en/types.json
locale/fr/quest_templates.json
mapadroid/db/DbPogoProtoSubmit.py
mapadroid/utils/questGen.py

Added support for pulling pre-defined quest text from quest_templates.json and added 4 new quests which will be used for February CD voting.

Support for February CD Voting Quests

---

mapadroid/db/DbWrapper.py
mapadroid/worker/MITMBase.py
mapadroid/worker/WorkerBase.py

Restart Counter now properly increments on the status page

---

mapadroid/worker/WorkerQuests.py

As I haven't tested levelmode during creation of #741 there seem to be a couple of non-breaking, but function-impairing problems.
Currently monitoring a device running levelmode, I'll collect the fixes I find necessary in here. Still ongoing, so maybe don't merge yet. I'll comment again when I think it's finished.

WIP: Quest fixes fixes :)

---

mapadroid/data_manager/modules/area_pokestops.py

WordingFix

---

mapadroid/db/DbWebhookReader.py

Currently, MAD logs only about quests and it's hard to debug which of those queries takes too long just from logs.

More debug logs for webhook queries.

---

scripts/SQL/rocketmap.sql

Fixes a syntax error in rocketmap.sql which I introduced in #764

fix syntax oops

---

mapadroid/db/DbWrapper.py
mapadroid/madmin/routes/statistics.py
static/madmin/templates/status.html

Delete&Reset status page entries

---

static/madmin/templates/status.html

Unicode emoji drawn different on Apple and it was black on black in darkmode. Still looking good, but we wanted green. Using font awesome now, already used in madmin.

Change to green checkmark, because Apple.

---

mapadroid/madmin/routes/statistics.py

Looks like someone abused from copy-pasting ;-)

Update Statistics page title

---

mapadroid/db/DbWrapper.py

Just to limit questions and search :P

More info in warning get_to_be_encountered

---

mapadroid/websocket/dummy_debug_rgc.py

So it is easier to debug devices.

Adding web socket adress to stdout in dummy_debug.py

---

mapadroid/worker/MITMBase.py
mapadroid/worker/WorkerMITM.py

Should be pretty self-explaining to the decision-makers :-)

Check distance only once, move log spam to debug

---

mapadroid/worker/MITMBase.py

Make sure to have proper distances for the recently introduced distance checks.
Could fix issues with quest / level / iv_mitm modes.

Improve distance to check against

---

mapadroid/db/DbWrapper.py
static/madmin/static/js/madmin.js

Upon initial load of the map all spawnpoints are loaded ignoring the given coordinates altogether, which is quite a waste.

Respect coordinates when loading spawnpoints

---

mapadroid/data_manager/modules/area_mon_mitm.py

Additional words, so it will be even more clear

---

mapadroid/db/DbWrapper.py
mapadroid/madmin/routes/statistics.py
static/madmin/templates/base.html
static/madmin/templates/statistics/statistics.html
static/madmin/templates/statistics/stop_quest_statistics.html

Separate Quest / Stop in own statistic page 
**New feature**
quest process status

Separate quest/stop stats

---

mapadroid/db/DbStatsReader.py
mapadroid/madmin/functions.py
mapadroid/madmin/routes/statistics.py
static/madmin/templates/statistics/spawn_statistics.html

Make that thing that cec did accessible to more people.

Show single geofence selector in Spawn Stats if a lot of data

---

configs/config.ini.example

Makes more sense here rather than raw stats section.
Some stupid wording/cleanup, again, if I was already here.

Moved setting to different section

---

mapadroid/db/DbPogoProtoSubmit.py

Updated possible dittos list

---

mapadroid/webhook/webhookworker.py

This is missing for #837 
Going for one if check, all or none of those values should be set at the same time.

Add catch rates to webhook data

---

mapadroid/db/DbSchemaUpdater.py
mapadroid/db/DbStatsReader.py
mapadroid/db/DbStatsSubmit.py
mapadroid/madmin/routes/statistics.py
mapadroid/patcher/__init__.py
mapadroid/patcher/trs_stats_detect_raw_split.py
scripts/SQL/rocketmap.sql

Split into two tables for speedier index on pokestop id and also for encounter_id for mons

Split raw stat detect for mons and quest/raids into separate tables

---

static/madmin/templates/status.html

After removing the 'Command' title the column is not wide enough and bootstrap is forcing new line between buttons :(

nowrap on buttons column in /status

---

mapadroid/data_manager/__init__.py
start.py

fix an issue where routecalcs were losing their instance in multi-instance systems

Multi-Instance On Boot Routecalc Instance fix

---

mapadroid/worker/WorkerFactory.py

I hope this will be more clear

Re-word error message, drop 'mappings'

---

mapadroid/worker/MITMBase.py

Device will only reboot during injection if reboot = true

---

mapadroid/ocr/screenPath.py

ist = is
No more screen detection - disabled ... = Screen detection is disabled

fix typo // shorten msg

---

mapadroid/mitm_receiver/MITMDataProcessor.py

Not debug message. This shouldn't happen a lot and when it happens it should be logged for benefits of "new" users.

Lower than level 30 enc IV's should be a warning

---

static/madmin/templates/settings_areas.html

Someone will use it, I hope :)

Direct link to wiki in area dropdown

---

locale/de/pokemonTypes.json

Gras is bad, I was told.

---

static/madmin/templates/settings_areas.html

copy-pasta, best pasta, I guess.

Cleanup of ortools message, was doubled

---

static/madmin/templates/madmin_apk_root.html
static/madmin/templates/settings_areas.html

Some frontend love :) 
Dunno what jabs commit does there, but whatever

Make MADmin beautiful again!

---

mapadroid/db/DbWrapper.py
mapadroid/madmin/routes/map.py
mapadroid/worker/WorkerMITM.py

PR as requested by @Expl0dingBanana :-)
Fix cellupdates view in MADmin + reduce `_check_data_distance` calls back to previous behaviour.

Flake8 fixes

---

mapadroid/utils/pluginBase.py

Fix Travis complains about 'file' being too generic.

---

mapadroid/madmin/routes/event.py

Typo.
Also no complains Travis or I kill you, thanks :D

Fix not being able to save event after flake8

---

mapadroid/madmin/routes/event.py

I encountered the issue that events werent able to be deleted.

fix not being able to delete event after flake8

---

mapadroid/mad_apk/abstract_apk_storage.py
mapadroid/mad_apk/apk_storage_db.py
mapadroid/mad_apk/apk_storage_fs.py
mapadroid/madmin/api/apks/apkHandler.py
mapadroid/madmin/api/apks/ftr_mad_apks.py
static/madmin/templates/madmin_apk_root.html

Allow the wizard to re-create the cache on-demand by calling an endpoint.  This is useful for multi-instance systems so the download only needs to go through on a single instance

Wizard re-cacher

---

mapadroid/utils/gplay_connector.py

Fixes an issue that caused RPi to be unable to download from the play store.

RPi wizard fix

---

mapadroid/madmin/routes/control.py
mapadroid/utils/updater.py

* Fix an issue where jobs could not be run from the control page due to a function signature error

Fix jobs that run from control page

---

mapadroid/worker/WorkerConfigmode.py

Maybe people will search configmode in Discord then and learn that it's one time thing and no reason to st

Bump configmode message to warning

---

mapadroid/db/DbSanityCheck.py
mapadroid/db/DbStatsReader.py
mapadroid/db/DbWrapper.py

Now compatible with ONLY_FULL_GROUP_BY which has been the default and
heavily recommended since MySQL 5.7. Fixed in a way that is also compatible with MariaDB.
+ some capitalization fixes for queries just so I could inspect them easier.

Fix statistics GROUP BY standard violations

---

mapadroid/utils/autoconfig.py

Darkmode fixes (and normal mode probably too)

---

mapadroid/madmin/api/autoconf/ftr_autoconf.py
mapadroid/madmin/routes/autoconf.py
mapadroid/tests/test_autoconfig.py
mapadroid/utils/autoconfig.py

Move the issues from a function into a class. This class allows for easier identification in web responses through headers.
Also fixes @JabLuszko angry travis failure

Autoconfig Issues class

---

static/madmin/templates/autoconfig_config_editor.html

* Fix an issue where RGC / PD selectors were not being checked on save

Fix Config Editor

---

mapadroid/webhook/webhookworker.py

It will be send always, even with eggs, just like CP set to 0.

Add evolution to webhook

---

mapadroid/madmin/api/autoconf/autoconfHandler.py
mapadroid/madmin/api/autoconf/ftr_autoconf.py
mapadroid/tests/test_autoconfig.py
mapadroid/utils/autoconfig.py

* use lowercase when saving email addresses for PD Configuration
* Add GET and PATCH methods to PD / RGC config

MADmin PD Configuration update

---

static/madmin/templates/statistics/spawn_statistics.html

also remove deleted class from convert link, that could backfire one day I guess :D

Fix delete button not doing anything on spawnpoints page

---

static/madmin/templates/phone.tpl

krzTrack again.
also moved href to be first, just because it looked odd.

Bring back confirm dialog for Reset data

---

mapadroid/madmin/routes/control.py

log MADMin ws clicks

---

static/madmin/templates/status.html

We have "all" now for people running more than 100 devices and want to overload theirs browsers.
(c) for Boby360

Add option for more entries in status page

---

mapadroid/data_manager/modules/pogoauth.py
mapadroid/tests/api/test_pogoauth.py
mapadroid/tests/test_autoconfig.py
mapadroid/utils/autoconfig.py

* Remove converting PD login to lowercase
* Update PogoAuth for google to convert to lowercase
Fix for #1005

Fix PD Case Sensitivity

---

mapadroid/data_manager/modules/device.py
mapadroid/madmin/madmin.py
mapadroid/mitm_receiver/MITMReceiver.py
mapadroid/tests/api/test_device.py
mapadroid/tests/test_autoconfig.py
static/madmin/templates/base.html

Mac enforcement

---

mapadroid/worker/WorkerQuests.py

Displayed walking speed was incorrect.
Two chars fix!

Fixed walking speed display

---

mapadroid/mitm_receiver/MITMReceiver.py

* Allow addresses to be specified in addresses.json if that file exists

Allow easier PD debugging

---

mapadroid/db/DbStatsReader.py

This MIN() breaks everything, delete it.

Fix Statistic for Worker

---

mapadroid/mitm_receiver/MitmDataProcessorManager.py

[03:54] 𝔈𝔵𝔭𝔩0𝔡𝔦𝔫𝔤𝔅𝔞𝔫𝔞𝔫𝔞: @JabLuszko🍏 (...) :open_mouth: PR plz

Fix a typo, because 🍌 wanted.

---

configs/token-dispensers.ini
mapadroid/mad_apk/wizard.py
mapadroid/tests/mad_apk/test_wizard.py
mapadroid/utils/gplay_connector.py

* Only state there is a new download available if the version codes are correct

Wizard GPlay Version Code Validation

---

locale/de/types.json
locale/en/types.json
locale/fr/types.json

AR scanning of pokestops are now supported

Support for new quest type

---

Dockerfile

Update the Dockerfile for new defaults

---

.travis.yml

Fix Travis - madmin enabled by default

---

mapadroid/utils/questGen.py

I know @fosJoddie has PR for whole QUESTGEN GO FAST, but still not merged.
Gonna put this there too... and update locales files later for items.

Quick fix for missing items in items

---

mapadroid/patcher/__init__.py
mapadroid/patcher/extend_trs_quest_pogodroid_190.py
scripts/SQL/rocketmap.sql

New PogoDroid brings more data.

Extend trs_quest.quest_reward length

---

static/madmin/static/style/MAD.css

Not a great color choice, but at least they stand out a little now. Still readable, just more ugly.

Make one of the datatables rows different color in darkmode

---

mapadroid/madmin/functions.py

* Fixed a name collision that caused state pages not to load

Fix a stats issue

---

CONTRIBUTING.md
README.md

* Create a new file that outlines some contributing information
* Explain the purpose of each make command

Include information on contributing

---

mapadroid/utils/global_variables.py

Fix PogoDroid URL from .de to .eu

---

mapadroid/db/DbPogoProtoSubmit.py

15 minutes for now. Should probably use lure/incident end times?

Actually set cache on pokestops

---

scripts/trunc_quests.sh

Sometimes it's easier to run a script than some manual SQL.

Add script to truncate quests.

---

static/madmin/templates/settings_singledevice.html

So Glee won't waste two weeks next time!

Add MAC address format to field description

---

mapadroid/utils/gamemechanicutil.py

Remove Paras from possibles ditto.

Update ditto list

---

mapadroid/utils/gplay_connector.py
mapadroid/utils/token_dispenser.py

Fixes an issue where the token dispenser code may incorrectly raise an error

Token Dispenser retry exception

---

mapadroid/webhook/webhookworker.py

Trying to add what's missing in the Poracle/RDM webhook flavor webhook.

WIP: Add missing quest conditions for poracle webhook kind

---

mapadroid/utils/gamemechanicutil.py

New event, should stay after the even according to pogo blog.

Adding Purrloin to list of possible Dittos

---

static/madmin/templates/events.html

Just changed the order of button and a.

Make the whole button a link, not only icon inside it /events page

---

mapadroid/data_manager/modules/area_mon_mitm.py

reverting an accidental commit by me. please merge asap

fix a critical bug from my pr

---

mapadroid/webhook/webhookworker.py

untested. not 100% sure this works

Fixing another #1120 bug (defining no webhook types wouldn't send all types)

---

mapadroid/webhook/webhookworker.py

Provides a little more info about the raid. Helps with determining which spawn pool the hatching boss is pulled from.

Added raid spawn time to webhook

---

mapadroid/db/DbPogoProtoSubmit.py
mapadroid/db/DbSchemaUpdater.py
mapadroid/db/DbWebhookReader.py
mapadroid/utils/gamemechanicutil.py
mapadroid/webhook/webhookworker.py

Do not update mon_id,form,costume,gender for detected mons in nearby and gmo
Refactor duplicated code for ditto detect on encounter wild+lured mon

Save the Dittos

---

configs/config.ini.example

Changed order here and there, removed outdated things, added descriptions how to get maddev api token

More description about maddev_api_token + cleanup

---

mapadroid/db/DbPogoProtoSubmit.py

Because no need to do more math per gmo :D

Move redis cache check to front

---

mapadroid/ocr/pogoWindows.py
mapadroid/ocr/screenPath.py

Extract from log 
```
[07-30 10:38:40.52] [            xxxxxx [        pogoWindows:597 ] [I] Screentext: {......................., 'text': ['', '', '', '', 'Froud', '', '', '', '4', '', '', '', '-', '', '“', '', '', '', 'aw', '', '', '', '_DECONNECTER', ',_', '', '', '', 'Sois', 'rel', 'eT', 'accra', 'Rete', '', 'autour', 'de', 'toi.', '', 'A', '\\', 'a', '', '', '', '']}
```

French Word for detect LOGINTIMEOUT on login page

---

static/madmin/templates/settings_devices.html

As requested in #1196, this PR will add bulk un/pause to the device settings page.

add bulk pause/unpause option (fixes #1196)

---

Dockerfile

I'm not sure if `libgl1-mesa-glx` is the smartest solution, but it works for me

Update to python 3.9 and add libgl1 library

---

mapadroid/ocr/screenPath.py

...only used and tested with x96 mini, so may not fit all sizes.

Scroll down in google consent screen

---

mapadroid/db/DbPogoProtoSubmit.py

People complain that they liked previous behavior more.

Move stats saving before cache check

---

locale/de/types.json
locale/en/types.json
locale/fr/types.json

- Add type 59 `Open {0} gifts` (All)
- Add type 42 and 57 that were missing (French)
- Reorder type 43 (German)
- Remove space for type 56 and 57 (English)

Update quest's types.json

---

.github/workflows/tox_testing.yml
mapadroid/db/DbPogoProtoSubmit.py

Fix a linting issue and remove py36 from github actions

Build Fixes

---

mapadroid/webhook/webhookworker.py

RDM seems to be using `with_ar` True/False so let's follow them?

Add quest_layer to webhook.

---

mapadroid/data_handler/mitm_data/RedisMitmMapper.py

intersection of set won't work for small areas (few cells) that you move from edge to center.

Fix LAST_POSSIBLY_MOVED updating.

---

mapadroid/utils/gamemechanicutil.py

Remove list of potential dittos, sync with master

Remove dittos mon_id check

---

static/madmin/templates/phonescreens.html

Dropping the `?madmin=1` param totally. Changing to 0 does not really works :P

Download fullscreens on click

---

mapadroid/data_handler/stats/PlayerStats.py

Add a "is not None" instead of praying to the Falsy gods

PlayerStats stats collect Falsy improvement

---

static/madmin/templates/settings_devices.html

Sort by device or by walker(name)!

Sort on table headers click

---

static/madmin/templates/phone.tpl
static/madmin/templates/phonescreens.html

I guess I should have fixed that `&` on first time, but yeah :<

Fix can't downloading screenshot after manual refresh

---

mapadroid/utils/global_variables.py

I guess this is gonna be standard for now, right? Just make life easier I guess :)

Link to async version of PD/RGC.

---

mapadroid/db/DbPogoProtoSubmit.py
mapadroid/mitm_receiver/SerializedMitmDataProcessor.py
mapadroid/route/RouteManagerBase.py
mapadroid/route/RouteManagerQuests.py
mapadroid/worker/Worker.py
mapadroid/worker/strategy/plain/AbstractWorkerMitmStrategy.py
mapadroid/worker/strategy/quest/QuestStrategy.py

Removes a bunch of overly redundant success messages and tries to make some position messages a bit easier to read in a console

Make logs narrower

---

static/madmin/templates/uploaded_files.html

This is not even one line fix, this is getting better and better :D

Fix missing delete button for INSTALLATION job

---

static/madmin/templates/quests.html

We need to do it prettier later (icon, name?), but let's have it like now for debug purpose.

Show layer number for quests browser

---

mapadroid/db/resource_definitions/Device.py
mapadroid/db/resource_definitions/Devicepool.py
mapadroid/mapping_manager/MappingManager.py

250 rare candy gang reporting in.

Update defaults, remove rare candy on items cleanup

---

static/madmin/static/js/madmin.js

Remove code that mistakenly was commited to only show cellupdate cells that was less than 50k (seconds/milliseconds?) old
needs a test before merge

reverse buggy code cellupdate code

---

mapadroid/ocr/screenPath.py

I have had this change locally for over a year. I don't know how more people don't complain about this feature missing for cellphones.
I set the click points off from my own devices. No guesses.

Add google consent support for 1080 and 2k screens

---

mapadroid/mapping_manager/MappingManager.py

This PR sorts the worker list before returning it, making selecting workers a breeze

Worker pick list was unsorted

---

mapadroid/db/DbPogoProtoSubmit.py

Kecleon incident is given priority over Leaders, Grunts, etc

Save Kecleon incident to db, as number 352 (master branch)

---

mapadroid/db/DbPogoProtoSubmit.py

Kecleon incident is given priority over Leaders, Grunts, etc

Save Kecleon incident to db, as number 352 (async branch)

---

mapadroid/db/DbPogoProtoSubmit.py

Kecleon incident is given priority over Leaders, Grunts, etc

Save Kecleon incident to db, as number 352 (main async branch)
