- scripts/import_allspawns.sh
This is the MAD spawnpoint importer. If you used to scan before and happen to still have your spawnpoints in your Monocle or Rocketmap database then you can use this script to import them to MAD. You must have the trs_spawn table already in your database and you must have filled out the Database portion of the MAD config file
> adding spawnpoint importer

- utils/webhookHelper.py
PA gym change hooks expects specific field names, so:
`gym_name` -> `name` so that it lines up with PA
Add description and url fields as well, both of which come from `gym_info.json`
***This needs tested***
I don't have a working version of MAD atm
> Gym Hook Fixes

- Dockerfile
OCR requirements are required for Quests scanning so better add those to Dockerfile so they are built into the docker image.
> Adding OCR requirements to Docker images

- configs/config.ini.example
This needs to be enabled in order for weather to be pushed to the database. It is not dependent on OCR thus the need for a description change.
> Detect Weather description change

- start.py
- utils/mappingParser.py
- websocket/WebsocketServer.py
This PR adds the functionality to dynamically update the settings for all workers on-the-fly when the mappings.json file has changed.
This enables easy editing of the settings and mappings in MADmin without the need for restarting the whole process to use the new ones.
> Dynamically reload settings from mappings.json

- start.py
- utils/walkerArgs.py
Quick implementation of `-or` / `--only_routes` mode, which will calculate missing route files while being able to keep your working instance running alongside it, as requested on Discord every couple of days.
Usually, calculating a complicated route at the beginning of the program causes a downtime. Running with -or separately will avoid this and shouldn't collide with the main instance in any way.
It's implemented as just a `sys.exit(0)` at the appropriate location in `start.py` when `-or` is set.
> Add only_routes mode

- worker/WorkerQuests.py
There's probably not a lot of worker accounts with a Mystery Box, but those fail to clear bag space without this little addition.
> Do not try to delete Mystery Box when clearing box

- madmin/madmin.py
- madmin/templates/base.html
- madmin/templates/index.html
I mean all the URLs are still active and there probably should be some checks/wider approach, but at least for now we can just stop showing links and confusing people while not running (gyms) ocr :-)
> Don't show OCR options in madmin if not running OCR

- worker/WorkerQuests.py
The title, basically. Should save a few seconds when clearing inventory space. Works as expected on my installation / devices.
May be bad style, I have no idea.
Also fixes `Raidpass` -> `Raid-Pass` :-)
> WorkerQuests: Only take new screenshot if something was deleted

- locale/quest.pot
- utils/questGen.py
Event task "evolve a meowth" is interpreted as "evolve a pokemon" in MAD - fixed to add in "evolve {0} {poke}" if a research task is about evolving specific species. Hopefully not breaking anything with existing "evolve pokemon"/"us an item to evolve"
> Add missing info about what pokemon to evolve if the task requires it

- configs/config.ini.example
- utils/walkerArgs.py
- webhook/webhookworker.py
A few webhooks only need raids and other need raids and mons.
Here is the extension that it is possible to enter your endpoint for each type of webhook.
Defaults to everything activated:
`webhook_url=http://example.org/foo/bar`
To activate certain options:
`webhook_url=[mon|weather|raid]http://example.org/foo/bar`
With multiple urls:
`webhook_url=[mon|weather]http://example.org/foo/bar,[raid]http://othersite.com/baz`
> Webhook URL extension for every type of webhook

- madmin/templates/base.html
Otherwise gets blocked as mixed content when accessing through https.
> fix jquery blockUI on https

- webhook/webhookworker.py
It's actually called webhook_submit_exraids in config.ini.example so I assume we using this name. If not just fix in config to the one used in webhooks.
> Fix a typo, I guess.

- db/dbWrapperBase.py
- db/monocleWrapper.py
- db/rmWrapper.py
- utils/questGen.py
- utils/version.py
- utils/webhookHelper.py
Currently, the quest webhook sends some data that is mostly not well processable by e.g. BookOfQuests.
After some discussions with the guy from BoQ, we found a solution to make the current quest webhook messages compatible.
Changes:
- also store and deliver `quest_template`
- include all non-string values correctly (int, float, json)
- fix the condition to be valid json
__As usual from my side: untested as it is__
_(I also have some changes in my own code base that enables compatibility with PokeAlarm dev, but this is not included here.)_
> Fix Quest Webhook

- requirements.txt
This causes new installs to fail when pip installing the requirements, 2.1.7 is available, so this changes the requirements.txt file to use 2.1.7
> mysql-connector==2.1.6 has been removed from PyPi

- db/monocleWrapper.py
- db/rmWrapper.py
Please double check if this make sense, but for all other types we use >= not only > and that would explain why I have some quest webhooks missing on edge cases like this:
```
2019-04-08 05:14:49,138 [    webhook_worker][ webhookworker:89][    INFO] Successfully sent payload to webhook. Stats: {"weather": 1, "gym": 16}
(...)
2019-04-08 05:14:49,252 [             leeco][  WorkerQuests:442][    INFO] Spin Stop
2019-04-08 05:14:51,763 [             leeco][  WorkerQuests:452][    INFO] Getting new Quest
(...)
2019-04-08 05:14:52,012 [             nexus][  WorkerQuests:442][    INFO] Spin Stop
2019-04-08 05:14:54,524 [             nexus][  WorkerQuests:452][    INFO] Getting new Quest
(...)
2019-04-08 05:14:59,320 [    webhook_worker][ webhookworker:89][    INFO] Successfully sent payload to …
```
> Fix missing quest webhooks in edge cases.

- madmin/madmin.py
Example:
create areas under "Mapping Editor" with name "test123" and name "test".
The first area is "test123" and second is "test" then try to delete "test".
Expected: 
"test" should be deleted, not "test123"
> fix delsetting in Madmin

- madmin/templates/phonescreens.html
In Firefox is the phonescreen not always reloaded when a screenshot or something is taken. 
With the CacheBuster it is reloaded.
> MADMIN: add cachebuster for phonescreen

- madmin/madmin.py
- madmin/templates/parser.html
We force two digits for minutes (just like the description by cec states ;)), so people won't end with 1:1, it must be 1:10 or 1:01. Whitespaces between hyphen allowed. This regexp validate for non-existing hours, so no more 25:49 or other typos.
No jquery btw. :-D
> Validate walkervalue.

- db/rmWrapper.py
Should probably be the same as line 777 (for mons).
As it is, it always says "(init)" when it shouldn't.
> fix "updating IV" log line in rmWrapper

- configs/config.ini.example
- utils/walkerArgs.py
- webhook/webhookworker.py
Adds a new optional argument `quest_webhook_flavor` that can be either default or poracle. 
If set to poracle, quest webhooks will be sent in a format that is compatible with PoracleJS :tm:
Includes a new try/catch block for quest gen in case something blows up.
Needs extensive testing by people using Poracle to ensure all quest conditions and rewards come through correctly.
> WIP Add support for Poracle compatible quest webhooks

- scripts/migrate_to_rocketmap.sh
1) use the old database credentials with sqldump. Otherwise sqldump may fail due to not having permissions
2) enhance the script to support single quotes in gym and pokestop names
> Enhance migrate_to_rocketmap.sh script

- db/monocleWrapper.py
- db/rmWrapper.py
- madmin/routes/statistics.py
Fix missing mons from "Recent Perfect Pokemon"
Some entries are lacking because of no matching records in `trs_stats_detect_raw`. This PR fixes it by skipping joining the two tables.
> Fix perfect IV statistics

- db/monocleWrapper.py
- db/rmWrapper.py
- webhook/webhookworker.py
Added gender support for webhook type "raid" which is supported by PA for example.
Also modified rm wrapper to pick up information to fill the needed gender data.
This additional gender information for raids is useful for Burmy, Snorunt etc.
> Added gender support for raid bosses

- route/RouteManagerQuests.py
The list of stops in the stops not processed might be populated with
stops that are no longer there for any reason. This is a quick
workaround that makes sure that we do not get stuck forever trying to
process these stops after the initial quest worker round.
> Ignore unprocessed stops that could not be found in stoplist

- db/rmWrapper.py
currently only the last 30 perfect mons will show on stats page, this change makes that number 300 and lets the statistics page control how many are shown via the drop down selector
> minor change to perfect mons on stats page

- configs/config.ini.example
- madmin/functions.py
- madmin/routes/path.py
- madmin/templates/base.html
- madmin/templates/quests.html
- utils/walkerArgs.py
As requested on discord a couple of times, `/quests_pub` is `/quests` without the MADmin header.
By default, normal auth settings apply. By setting `-qpub` / `--quests_public`, `/quests_pub` and `/get_quests` + ` /asset` will not require auth anymore.
In case my implementation sucks, please roast me :-)
> Add MADmin /quests_pub endpoint

- worker/WorkerQuests.py
QOL update: When waiting before spinning the next pokestop, display the actual next action time.
Also floor the sleep time for better readability
> Display next action time when sleeping

- worker/MITMBase.py
This will make handling the MARKETING screen more reliable.
> retry check_windows while waiting for injection

- db/monocleWrapper.py
- db/rmWrapper.py
This fixes most of the malformed pokemon after event and/or weather changes. For example the falsely boosted community event mons after the event hours have ended.
> Fix for malformed pokemon after weather/event changes

- webhook/webhookworker.py
**I don't know why my Git closed #275 so reopen:**
Users reporting in Discord that they have missed some 100% IV Mons in their webhook clients. They were _probably_ not sent by MAD.
While reading the code I noticed that the `last_check` in webhookworker.py could cause a small race condition: If the query or the for-loop is slow we could miss Mons.
**Example:**
12:00:00:00: Big webhook preparing to send. Loop is slow because big amount of data.
12:00:01:00: Webhook finally sent. => `last_check` = 12:00:01
But the async scanner found a Mon:
12:00:00:50: Mon inserted into database with `last_modified` = 12:00:00
12:00:10:00: Next webhook preparing to send with Mons between 12:00:01 and 12:00:10.
=> Mon from 12:00:00:50 is missing.
~~So I added a 5 seconds interval to the query. Maybe this is …
> Potentially webhook fix

- db/rmWrapper.py
- webhook/webhookworker.py
Added grunt type support to database and webhook type "pokestop".
Also modified rm wrapper to pick up information to fill the needed data.
This additional type information for invasions is useful to hunt for specific mon types.
This uses the same naming scheme as rdm / pmfs for easier compatibility.
> Added grunt type to db and pokestop webhook

- db/dbWrapperBase.py
- utils/version.py
Manually check if index exists (use >= 1, because those indexes can be multi column) and then drop and re-create it. Syntax DROP INDEX IF EXISTS is MariaDB syntax, not MySQL syntax - no "IF EXISTS" there.
Also added column check to previous versions so it will stop complaining in logs (after removing version.json) and confusing people with red errors.
> Drop index if needed, old syntax not MySQL compatibile

- utils/logging.py
Changes how log level is determined.
The old method did `11 - arg.log_level`. That wasn't flexible and broke MAD if you set it to anything too high.
New:
* Doesn't crash when you set verbosity to above the limit, e.g. `-vvvvvvvvvvvvvvvvvvvvv`. Instead it sets it to the highest available log level and shows a `DEBUG` message (see screenshot).
* Setting log level via name (e.g. `"DEBUG"`) is now case insensitive.
* Shows the name of the log level in console.
* Debug log level steps no longer have to be 1 by 1. Jumps can be whatever they want, it'll automatically pick the right level in the sequence.
* Replaced magic numbers by log level label (`map.get(label)`) via the log level map.
Dungus Maximus helped me test it. @LegitDongo 
More testing is definitely welcome, for both the numeric `-v` …
> Improve logging verbosity settings.

- webhook/webhookworker.py
We have that data already, just use it :)
webhook receivers can now distinguish between normal eggs and ex-raids eggs (not 'ex-raid eligible gyms'). Game (and MAD) does sent ex-eggs info to everyone, but not what actually hatched from those - you need invite for that.
> is_exclusive in raid webhook

- webhook/webhookworker.py
PoracleJS is using the `weather` key to determine if a pokemon has a weather boost however MAD defaults to using using the `boosted_weather` key. https://github.com/KartulUdus/PoracleJS/blob/3368ec2913de9b5407096e9842cb739b57dc4c46/src/controllers/monster.js#L137
This fixes the problem if someone sets the `quest_webhook_flavor` to poracle however this might cause an issue if someone uses another webhook for pokemon alerts?
Would the dev team rather create a new "mon_webhook_flavor" config option? Or can we just send both keys?
```json
mon_payload["boosted_weather"] = mon["weather_boosted_condition"]
mon_payload["weather"] = mon["weather_boosted_condition"]
```
I've tested this patch works but again maybe it's not the best solution long term.
> fix: Correct payload key for porcale mon weather

- configs/config.ini.example
- utils/walkerArgs.py
- webhook/webhookworker.py
By default MAD do not send non-iv'd pokemon via webhook if they are on ANY IV list.
It's still marked as #TODO and I don't want to mess with @sn0opy vision how to do it - this way we can safely enable sending non-IV'd mons to webhook, I guess.
Default behavior is not changed - user must uncomment a line in config.ini to have it working.
**WARNING**: Your webhook receiver must support getting same encounter twice - once with IVs, once without IVs. For example PokeAlarm does this only in dev branch.
> Ability to send non-iv'd mons (that are on iv list) via webhook.

- utils/logging.py
We need tuple here (and there one more return without tuple, will check later)
> Fix loglevel tuple when nothing specified

- SQL/rocketmap.sql
- scripts/migrate_to_rocketmap.sh
Complete rework of the Monocle/RDM to Rocketmap Migration script
- Added User interactivity (easier than config for one-time script);
- Script will now create DB by itself.
- Script will now create the full RM schema by itself.
- Script will also take over all trs tables in order to make switch as transparent as possible.
- Checks added for DB connectivity before proceeding.
- Checks that target DB doens't already exist before proceeding.
I also added missing column in RM schema for trs_quest to make migration easier.
Tested successfully migrating my Monocle DB to RM. Probably needs testing from a RDM user as I don't have a DB to test it, but should be ok as most queries are the same. Please report any issue found.
> New Monocle/RDM to RM Migration script

- madmin/routes/map.py
Leaflet handles very zoomed out views by simply adding multiple worlds. This causes coordinates from it to not always be inside [90, 360] - this fix makes sure we don't duck up saving of geofences.
> Multiworld support when saving geofences from madmin

- route/RouteManagerBase.py
Fixes [this tiny line](https://github.com/Map-A-Droid/MAD/commit/a758ecb70b1da53189e2c26bfaa4256bde4f8107#diff-8fbcc2a0206b6ea34f14ac0cedbb4cb7R697).
And then I couldn't stop myself from updating the other log lines in the file to be consistent.
All the `str()` entries are a bit too much. Also need a linter config, and for the linter to be applied every commit, to be consistent in code style.
There's a `.flake8` config file, but none of the code passes `flake8`.
**Only affects the route_distribution branch.**
> Fix logging line.

- madmin/routes/map.py
There are bounds there in map definition now, there is no need for modulo 360/90.
Btw. it was broken before too.
```
>>> 80%360
80
>>> -80%360
280
```
> Fix saving geofence coords for negative values

- db/dbWrapperBase.py
- madmin/templates/status.html
- utils/version.py
- worker/MITMBase.py
- worker/WorkerQuests.py
Allows (quest) workers to save the current sleep time in status table so it can be seen in madmin worker status page like this: 
Why? Because then you can see if it's actually stuck or just on a long sleep time between areas.
Tested a bit, but more tested needed 🙏 
Also fixes some missing columns in the code for new dbs `trs_status` table
> Show sleep time in status page

- mitm_receiver/MITMDataProcessor.py
- mitm_receiver/MITMReceiver.py
- mitm_receiver/MitmMapper.py
Every submitted GMO look at cellsid in that GMO and if those cellsid changed from last (saved) set current timestamp to now - as 'last time worker possibly moved'. It's used now in that amazing /status/ JSON - just to monitor of your device isn't stuck somewhere - maybe routemanager died, maybe no more coords, maybe RGC died.
> 'Last possible moved' timestamp in /status/

- madmin/templates/base.html
The URI generated when clicking on a job when not in the document root creates an invalid URL and displays a 404.
> Fix for accessing jobs from subdirectories

- utils/data_manager.py
default_sort was not defined for walkerarea causing a 500 when querying /api/walkerarea.  This change validates the key exists so we do not lookup a NoneType.
> Fix for preventing 500's when querying walkerareas

- madmin/templates/base.html
:highprio: PR, as always. But the icon does not show on the Settings page. Either its a caching issue (eventho i've tested it with a different device and incognito mode) or somethings not right. The only difference i was able to spot is, that the device page loads sub pages. But those sub pages always refer the parent page (settings.html) which is referring base.html 🤷‍♂
> re-add the favicon

- db/rmWrapper.py
- madmin/routes/map.py
- madmin/static/js/madmin.js
- madmin/static/style/madmin.css
- madmin/templates/map.html
As requested in #453 this PR will add an extra option to view all stops in the current view on the MADmin map. This is still highly WIP and requires some finetuning here and there. 
Their color does not change based on the lure or incident but at least the popup will show the current event without the actual type
> Show all stops on the madmin map

- utils/adb.py
New import and fix check.
Reason:
The package name has been renamed from ‘adb’ to ‘ppadb’
From version v0.2.1-dev, the package name has been renamed from ‘adb’ to ‘ppadb’ to avoid conflit with Google google/python-adb
> Fix import and check for ADB support

- madmin/api/apiHandler.py
- madmin/api/apiRequest.py
- madmin/api/apiResponse.py
- tests/api/api_base.py
- tests/api/global_variables.py
- tests/api/local_api.py
- tests/api/test_area.py
- tests/api/test_auth.py
- tests/api/test_device.py
- tests/api/test_devicesetting.py
- tests/api/test_monlist.py
- tests/api/test_walker.py
- tests/api/test_walkerarea.py
Created basic unit tests for the API.  It is not the most elegant method, but to test navigate to tests/api and run '<your_python_interpreter> -m unittest'.  It is currently not configured to read from the configi.ini so you must update the file if you have a password and are not running on port 5000.
> Unit tests

- madmin/templates/quests.html
- madmin/templates/status.html
stateDuration is set to two hours by default. Randomly (never could get pattern, those 2 hours seems like a fit) the /status page would forgot how many devices I wanted to show and it will switch back to default 10 devices. 0 means infinity.
Also fix (enable it) for /quest page. @Expl0dingBanana will give feedback, he is actively using it.
Someone please test and if the problem of /status randomly switching back to 10 devices will be fixed I will edit PR for all datatables we have there in other subpages.
> Possibly fix dropping settings for /status and /quest page

- madmin/routes/config.py
An issue was identified where Mon IV Lists would save but not be correctly rendered into the UI.  The data_manager call has been updated to include the required parameters.
> MonIVLists not populating in UI

- madmin/templates/uploaded_files.html
I like these icons more, and they come default with fontawesome
Example:
The new trash can icon will be https://fontawesome.com/icons/trash-alt?style=solid
> Jobs Page Icons

- route/RouteManagerBase.py
- route/RouteManagerFactory.py
- route/RouteManagerRaids.py
- route/routecalc/ClusteringHelper.py
- route/routecalc/calculate_route.py
- utils/MappingManager.py
- utils/s2Helper.py
This is an update of PR #315. Previous PR was based on dev branch and needed some manual merge wich was applied in the current.
Standard way to cluster is to pick a coordinate, find one coordinate furthest away but within visual radius. Then take a circle around the center of the two coordinates and remove coordinates within the circle from the list of coordinates to cluster.
This PR just changes the circle to a region of S2 cells that are touched by the circle. This way removing all coordinates that are actually seen from the list.
The effect is of course dependent on the density of gyms. For me it reduced the number of coordinates from 100 to 84, I still scan all gyms.
-added facilities to pass S2 cell information from utils/MappingManager.py to actual route calculation
Old algorithm …
> Change route calculation to consider S2 cell level for viewing radius.

- db/dbWrapperBase.py
Stop overwriting lastProtoDateTime with Null value.
Added an If so that if the new value has à 0 lenght, it doesn't get updated.
This way we keep the real lastProtoDateTime in the trs_status table.
> Stop Overwriting lastProtoDateTime with Null values

- db/dbWrapperBase.py
- db/rmWrapper.py
- madmin/routes/statistics.py
- worker/MITMBase.py
- worker/WorkerBase.py
- worker/WorkerConfigmode.py
Fixes  one of the issues mentioned in https://github.com/Map-A-Droid/MAD/issues/444#issue-509615654 and tracks the worker status in `trs_status` per running MAD instance.
It requires `ALTER TABLE trs_status DROP PRIMARY KEY, ADD PRIMARY KEY (instance, origin);` to span the primary key over `instance` and `origin`. I haven't added this particular automation yet, but I propose to extend `DbWrapperBase._check_create_column` to modify keys along with a column.
> Track worker status per MAD instance

- madmin/api/apiHandler.py
- tests/api/test_walker.py
The API was always returning an empty list if it was a list of URIs.  This has been addressed and a unit test has been added to validate the issue moving forward.
> Fixed API returning empty list for resources

- madmin/api/apiHandler.py
- madmin/api/modules/ftr_area.py
- madmin/api/modules/ftr_auth.py
- madmin/api/modules/ftr_device.py
- madmin/api/modules/ftr_devicesetting.py
- madmin/api/modules/ftr_monlist.py
- madmin/api/modules/ftr_walker.py
- madmin/api/modules/ftr_walkerarea.py
- madmin/routes/config.py
- madmin/templates/settings_singledevice.html
- madmin/templates/settings_walkerarea.html
- tests/api/test_walker.py
Device and WalkerArea were not correctly rendering on an empty configuration
Usability enhancement when creating walkerareas with no areas defined
Fixed an issue where API was not using the 'empty' value if it was a required field
Fixed an issue creating a new area where a 500 was returned if mode was not specified
> Ui pages not rendering

- db/dbWrapperBase.py
according to @fosJoddie so I guess we can delete that from blacklist
> STRICT_TRANS_TABLES is working with MAD

- madmin/api/apiHandler.py
- madmin/api/modules/ftr_walkerarea.py
- tests/api/test_walkerarea.py
Fixed the walkervalue unittest that did not catch the issue from the previous change.  The required change for walkervalue to be an empty string and required has been implemented (again...).
Fixing the unittest should make sure this regression does not happen again
> Walkervalue fix

- db/dbWrapperBase.py
- db/rmWrapper.py
- madmin/routes/control.py
- madmin/templates/settings_singledevice.html
- route/RouteManagerBase.py
- route/RouteManagerFactory.py
- route/RouteManagerIV.py
- route/RouteManagerLeveling.py
- route/RouteManagerMon.py
- route/RouteManagerQuests.py
- route/RouteManagerRaids.py
- utils/collections.py
- utils/version.py
- worker/MITMBase.py
- worker/WorkerQuests.py
Introducing: A levelup mode that you can restart quickly!
How? - Just sit back and let the magic of databases remember where you've been so route coordinates can be skipped quickly in quest level mode.
note: this works for areas in mode pokestop with "level" set to true.
Caveats: Currently only one worker can visit an area before it is forever tainted as visited. A better version is in the works but requires more work and maybe a new mode.
FAQ:
Q "one worker finished up a quest area and now the next worker one just says there's nothing to spin"
A run `DELETE FROM trs_visited WHERE origin'thatoldworkerorigin'` and restart MAD
Q how come there are no more questions
A I run out of time
> Real levelup mode that remembers what is already visited

- utils/version.py
Specify Collation on trs_visited table creation in order to avoid `Illegal mix of collations` if DB is configured with a default collation different from utf8mb4_unicode_ci
> Trs_visited Table Collation.

- madmin/routes/control.py
Installing a job via DeviceControl -> Install Job was returning a HTTP500.
> install_files failure

- madmin/api/modules/ftr_device.py
- madmin/static/js/madmin_settings.js
Device now supports None for reboot and cool_down_sleep.  Fixes #525
> None supported for 2 additional device settings

- madmin/api/apiHandler.py
- tests/api/test_walker.py
The issue that is addressed by this change is being unable to save 'required' values that have an 'empty' string in their definition if a None / Null value is sent.  For example, you were unable to update a walker if you sent a null 'setup' value
> Better null handling for incoming API values

- route/RouteManagerBase.py
if we are redoing routepool distribution and a worker disconnects we
no longer will crash and burn but instead carry on in some way
> race condition fix for routepool manager

- madmin/api/modules/ftr_device.py
- madmin/api/modules/ftr_devicesetting.py
- worker/WorkerQuests.py
Depending on the performance of the scanner device, a single inventory cleanup routine (clicking trashcan, tap&hold the plus symbol for 3000 ms, confirming item deletion) may just delete as little as 20 items, and there's a hard limit of 10 cycles of the routine, usually leaving Pinap berrys piling up.
This pull request introduces two options on device/shared settings level:
* `inventory_clear_item_amount_tap_duration` to set the duration for tapping the plus symbol
* `inventory_clear_rounds` to change the number of attempts
This is just a quick remedy to the problem. A better approach would OCR the number of items and then press the plus symbol until the number is actually reached.
> Add config options to clear inventory items

- worker/WorkerMITM.py
Two of the three conditions are dead code in the current order.
> Fix order to auto-detect cooldown time

- tests/api/test_walker.py
- utils/data_manager.py
Removing a walkerarea from a walker did not trigger deletion of the walkerarea.  This changes allows walkerareas to be removed upon removal from a walker, pending it not being aligned to another walker.
> WalkerArea Removal Fix

- db/rmWrapper.py
Fixes a bug which makes `stop_from_db_without_quests` query all ever-seen stops without a quest, instead of just those within the bounding box around the geofence. 
This mistake doesn't bubble up to the caller because afterwards the stops are filtered to be within the fenced area, but it might contribute to higher memory consumption on databases with many pokestops.
> Fix SQL in quest scan query (potential RAM eater)

- locale/en/pokemon.json
Correct spelling of Cofagrigus in en/pokemon.json
resolves #518
Thanks madBeavis
> Correct Cofagrigus spelling in en/pokemon.json

- locale/de/items.json
fixes #530 . Amount and Pieces are not that easy to translate since thats hardcoded in the MADmin template.
> fix Silberne Sananabeere

- madmin/routes/statistics.py
Fixing type mismatching, maybe from mysql client. This will bringt back the mons statistic working with mysql 8
> Fix Decimal interpretation ending in TypeError - so cast to float

- route/RouteManagerBase.py
The PrioQ thread was being shutdown when there were no more workers in the RouteManager.  During the shutdown / initialization, the flag was never set to allow the PrioQ thread to start up.
> PrioQ Thread fix

- start.py
Currently it doesn't quit on Python 3.5 - 3.0 because `py_version.major < 3` evaluates to false and so the minor version isn't checked at all
> Flawed version check

- madmin/static/js/madmin.js
Currently on the map in MAdmin the "Last mon seen" is showing the last confirmation (last_non_scanned) even if MAD has seen a spawn more recently (last_scanned). Variables have been swapped. Better explained in my Discord screenshot below.
> Fix "Last mon seen" in MAdmin

- madmin/static/js/madmin.js
- madmin/templates/quests.html
Burmy/Spinda quest rewards have form=0 in the game data and therefore in the database. On the quest page, Spinda is already mapped, but Burmy isn't. On the map page, there's no need for any mapping, as the whitewillem assets already provide an icon for form 0.
> Map burmy quest

- webhook/webhookworker.py
Lack of item in files stops generation of quest webhook - this should be an error, not a warning. It stops from sending it to the receiver.
> Change logging to error on building quest webhook

- ocr/pogoWindows.py
- ocr/screenPath.py
I sorted the screentypes after their numbers.
Added OCR texts to detect banned accounts.
Added detection of a warning strike by comparing the most present color which is 16,24,33 when the strike is displayed.
Returning player screen comes after selecting the birthdate.
Account type selection comes after pressing "returning player"
> Sort screentypes and detect bans

- worker/WorkerBase.py
This seemed to be the best location to put this, as it only needs to be done once per boot.
Tested working on my devices, will just silently fail on devices that don't vibrate (TV boxes).
> Attempt to disable vibration when starting pogo

- db/DbSchemaUpdater.py
- utils/data_manager/modules/devicepool.py
This feature was requested in the mad-dev channel.  The user would like to be able to set this via device pools as there is a 'none' option on the device.
> Added screendetection to device pools

- db/DbSchemaUpdater.py
- db/DbWrapper.py
- db/madmin_conversion.py
- utils/version.py
In #594 the alter table was being applied prior to the tables being created.  This did not allow the tables to be correctly initialized prior to the alter table and causing the update to fail
> Fix update order for devicepools

- madmin/api/apiHandler.py
- madmin/api/modules/ftr_area.py
- madmin/api/modules/ftr_routecalc.py
- madmin/templates/settings_areas.html
- utils/data_manager/modules/area_pokestops.py
- utils/data_manager/modules/device.py
Moved the RPC method for route recalculation from /api/routecalc to /api/area.  This is a more logical place as the old method required you to know the routecalc_id and the area_id while the new method is only the area_id
> Move RPC method for route recalculation

- utils/version.py
During the upgrade process for v19 it alters trs_status to use instance_id versus instance.  If the same device exists twice (one with and one without an instance) it will cause an error during the upgrade.  This change addresses that issue to notify it is removing non-instanced devices prior to altering the table
> Fix upgrade issue around non-instanced devices

- madmin/api/__init__.py
- madmin/api/apiHandler.py
- madmin/api/modules/ftr_area.py
- madmin/madmin.py
- madmin/routes/config.py
- madmin/routes/control.py
- madmin/routes/map.py
- madmin/routes/statistics.py
- madmin/static/js/madmin.js
- madmin/templates/settings_areas.html
- mitm_receiver/MitmMapper.py
- mitm_receiver/PlayerStats.py
- route/RouteManagerBase.py
- route/routecalc/calculate_route_optimized.py
- route/routecalc/calculate_route_quick.py
- tests/api/test_geofences.py
- utils/MappingManager.py
- utils/data_manager/modules/device.py
- utils/data_manager/modules/geofence.py
- utils/data_manager/modules/resource.py
- utils/data_manager/modules/routecalc.py
- utils/version.py
- utils/walkerArgs.py
- adding a new devices no longer requires a restart of MAD
- Fix for #599 (idle devices not showing on status page)
- Routecalcs
- Ad-Hoc recalculation does not remove the old calculation until finished
- Ad-Hoc recalculation is only available when running in start.py  (short-term goal is to deprecate configmode.py once the mapping.json requirement is removed #617 and use a flag to disable workers from connecting)
- Route recalculation now shows the progress when performing optimized recalcs. The update percentages is tiered based off the number of elements.
- Recalculation can now occur if the data-manager is in an idle state
- GeoFences
- Geofences drawn on MADmin map can now include spaces
- Geofences are validated prior to saving.  This will prevent an invalid GeoFence from crashing …
> QoL updates

- utils/data_manager/modules/geofence.py
- utils/data_manager/modules/resource.py
The implementation of validate the Geofence was causing the API to incorrectly report issues between calls.  This caused error codes to be returned that were not valid and prevented the data from being processed.  All 90 unit-tests pass with this change.
> Fixed an issue where the API was incorrectly reporting issues

- utils/data_manager/__init__.py
- utils/data_manager/modules/area.py
- utils/data_manager/modules/resource.py
The old base resources did not support multi-instance systems and caused the API to have unhandled exceptions
> API now supports multi-instance deployments

- configmode.py
- db/PooledQueryExecutor.py
- start.py
- utils/convert_mapping.py
- utils/version.py
This PR allows for a new system to be setup from scratch and fixes several issues where multi-instance MAD instances were not converting correctly.
To test the multi-instance conversion:
1)  Convert to DB
2)  Edit config.ini and add status-name and set it to a value other than mad.  If this is already set, change the status name
3)  Roll back version.json to 16.
4)  Re-Run the upgrade.
To clear out from a multi-instance conversion you can run the following queries (where instance_id is from madmin_instance)
DELETE FROM settings_device WHERE instance_id = <instance_id>;
DELETE FROM settings_walker_to_walkerarea WHERE walker_id IN (SELECT walker_id FROM settings_walker WHERE instance_id = <instance_id>);
DELETE FROM settings_walker_to_walkerarea WHERE walkerarea_id IN (SELECT walkerarea_id …
> New Instance Setup + Multi-Instance Conversion

- madmin/api/resources/resourceHandler.py
- tests/api/test_area.py
The API restructuring (#631 ) caused an issue where incoming RPC was being translated into backend objects.  This is not possible and was causing a traceback.
A unit-test has been added to validate RPC functionality moving forward.
-m unittest
...........................................................................................
----------------------------------------------------------------------
Ran 91 tests in 4.527s
> RPC Translation issue

- route/RouteManagerBase.py
- utils/MappingManager.py
Route calculation is almost non-blocking on boot.  If a route is not calculated it will perform a quick calculation.  Once the quick recalculation is finished a new thread is started to perform ad-hoc recalculation which is non-blocking.
Implementation for #566
> Route calculation on startup is non-blocking

- configmode.py
- db/DbWrapper.py
- db/PooledQueryExecutor.py
- db/madmin_conversion.py
- madmin/api/resources/ftr_area.py
- madmin/routes/config.py
- madmin/templates/settings_areas.html
- start.py
- utils/data_manager/__init__.py
- utils/data_manager/modules/area.py
- utils/data_manager/modules/resource.py
- utils/data_manager/modules/routecalc.py
During route recalcuation the UI now displays an icon showing that it is being being recalculated.  The 'areas' page now checks the status every 5 seconds to determine the status of all recalcuatlions fro all areas.  If the route is being recalculated it cannot be triggered again.
The schema for routecalcs has been updated to include the status (recalc_status) which states if the recalculation is running and when the last time the route was re-calculated.  These values are reset on boot since any previously running thread has been ended
> UX for route recalulation

- madmin/api/resources/ftr_device.py
- madmin/routes/control.py
- madmin/templates/settings_devices.html
- madmin/templates/settings_singledevice.html
- tests/api/test_device.py
- utils/data_manager/modules/device.py
Implementation for #628 
Enables bulk-update functionality on the devices page for clearing level-up data.  This functionality has been moved to the API as RPC
> Bulk clear level-up data

- db/DbWrapper.py
- mitm_receiver/MitmMapper.py
- mitm_receiver/PlayerStats.py
- route/RouteManagerBase.py
- route/RouteManagerLeveling.py
- route/RouteManagerQuests.py
- route/routecalc/calculate_route_quick.py
- worker/WorkerQuests.py
Should make quest level mode be more memory friendly, especially for large routes.
Changes:
- Each worker will get their own list based on what has been visited before
- A worker will use the saved routecalc as long as there are more or equal unvisited stops in db
- If there's fewer unvisited than the routecalc a recalc of route WILL happen. This might have negative impact on very large routes with a low number of stops in the routefile. Make sure you're on quick calc mode for those cases.
**Note**
- There's only one list of stops considered to ignored. This means if more than one worker is in the area and one worker fails the spinnable check, it will be added to the ignore list for everyone.
- Whenever a worker joins an area, all worker routes will be recalculated.
> Refactoring of quest level mode

- db/DbPogoProtoSubmit.py
- db/DbSchemaUpdater.py
- db/DbWebhookReader.py
- webhook/webhookworker.py
Added costume support for webhook type "raid" which is supported by other receivers.
Also modified files to create db column and pick up information to fill the needed data.
This additional costume information for raids is useful for the currently costumed raids.
> Added raid costume support to db and webhook

- ocr/pogoWindows.py
- ocr/screenPath.py
- ocr/screen_type.py
- websocket/WebsocketServer.py
- worker/MITMBase.py
- worker/WorkerBase.py
- worker/WorkerQuests.py
Basically bugfixing for multiple issues
- Moved ScreenType enum to ocr/screen_type.py and also commented the values (which I hope I got right...)
- Changed naming of WorkerBase._check_windows to WorkerBase._ensure_pogo_topmost along with most of its body. Removed the == ScreenType.POGO check in the while-condition in order to handle all screens. This is achieved by also lifting conditions for the same-screen-checks to trigger for all ScreenType != ERROR
- Refactored WordToScreenMatching.detect_screentype with 2 new methods splitting up the previous logic (namely __evaluate_topmost_app and __handle_screentype). While doing so, I added all possible enum values to __handle_screentype in order to at least log the types. This construct should be thought over anyway considering …
> Refactor screen handling

- db/DbWrapper.py
- db/madmin_conversion.py
- route/RouteManagerBase.py
- route/RouteManagerMon.py
- utils/data_manager/modules/area_mon_mitm.py
fixes https://github.com/Map-A-Droid/MAD/issues/579 by not dropping the prio q on recalculation for mon_mitm, but also reducing recalculation to one per 59 minutes,
fixes https://github.com/Map-A-Droid/MAD/issues/596 by ditching the complicated database query and just fetching all spawns for the next hour instead.
Both of these changes are feasible, because once all spawn / despawn times are known, the prioQ for mon_mitm actually just becomes a line sorting the spawn points by their spawn times. No actual prioQ flexibility is needed in this mode. It should lead to more robust and humanly understandable scanning behaviour. Also, I added a little code to check each prioQ event against the `remove_from_queue_backlog` threshold, because otherwise this would only happen during prioQ …
> prioQ fixes for mon_mitm, little improvements, logging

- madmin/routes/map.py
- madmin/static/js/madmin.js
- madmin/templates/map.html
Baiscally what this does is, it adds surrounding L15 S2cells to each raid route coordinate to make it more clear what is being scanned and what not. 
Todo but not actually blocking this to be merged:
- render cells in JS, not in Python on the server
- use correct, dynamic radius depending on the latitude (discussed on Discord)
> Add s2 cells for raid route coordinates

- db/DbWrapper.py
- utils/version.py
resolves #625 (also resolves #443 😃 ) and should enable multi-instance, multi-DB from a single MAD directory.
As we've pretty much moved everything possible into the database now, it's just logical to make this change.
Tested locally by playing around with the `current_version` value in `utils/version.py` and looking at the log outputs and database and subsequently moved to my production instances without any apparent issues.
Please notify or edit especially if there's any issue with the changes to `db/DbWrapper.py` - it seems to work but I'm not sure if it's correctly implemented within the system of `db/` files and classes/methods.
> move internal version from version.json to DB

- madmin/routes/map.py
- route/RouteManagerBase.py
- utils/MappingManager.py
Implementation of FR #479 
If an area has multiple workers the map will show the full route and the routearea each workers responsibility.  The device names will be appended to the area name to indicate its a subroute.
> Route breakout per worker

- route/RouteManagerBase.py
- route/RouteManagerMon.py
fixes #673: large areas can get stuck clustering a huge amount of events. The effort of clustering probably rises exponentially with the number of events, thus it can be an issue.
It's more a quick workaround than a full fix. A pretter fix would somehow dynamically find an acceptable prioQ calculation interval, but the 10 minute interval will cut the number of events to cluster into 1/6 of the previous number and should quickly help affected users.
Removing the warning is easier than going through the latest list two times. Warnings will still show up from events being dropped during the scanning process, so this one shouldn't be strictly required.
> Fix #673 - calculate mon_mitm prioQ every 10 minutes

- madmin/templates/phonescreens.html
Without these modifications you could only have a maximum of 3 screens,
no matter how much white-space you had or which zoom level you used.
Now its responsive to zoom and adds more than 3 screens on higher resolutions.
> Improved amount of device screens for higher resolutions

- commands.json
- configmode.py
- db/DbSanityCheck.py
- db/DbWrapper.py
- db/PooledQueryExecutor.py
- madmin/api/__init__.py
- madmin/api/apiHandler.py
- madmin/api/apiRequest.py
- madmin/api/apks/__init__.py
- madmin/api/apks/apkHandler.py
- madmin/api/apks/ftr_mad_apks.py
- madmin/api/global_variables.py
- madmin/functions.py
- madmin/madmin.py
- madmin/routes/apks.py
- madmin/templates/base.html
- madmin/templates/madmin_apk_root.html
- requirements.txt
- start.py
- utils/apk_util.py
- utils/global_variables.py
- utils/updater.py
- utils/version.py
- websocket/communicator.py
This allows MAD to host any uploaded APKs.  This allows for local file-transfers when installing APKs for ATVs.
Testing:
Upload a file (there are no version checks or validation you are using the correct type [pogo, pd, rgc])
wait for the screen to refresh.  Once refreshed you should see your file.  You can download the file @
`/api/mad_apk/<apk_type>/<arch>/download` (ie `/api/mad_apk/pogo/armeabi-v7a/download`).  Authorization for this page are the same requirements as RGC / PD.
To-Do list (future releases)
Move the upload to the API
Update Jobs to use these local files
Have MAD auto-find newer versions and import (probably a config flag)
> Initial development of MADmin hosted APKs

- mapadroid/db/DbWrapper.py
- mapadroid/utils/version.py
- mapadroid/worker/MITMBase.py
- mapadroid/worker/WorkerConfigmode.py
- static/madmin/templates/status.html
The table, trs_status, was converted from datetime to timestamp.  This is to store all numbers in epoch vs the local timezone.  Setting the device idle mode now works correctly
Fixes:
- Adjust the columns to be TIMESTAMP so the values are stored as epoch (trs_status)
- Idle mode is now shown correctly and no longer produces invalid SQL during insert
- Links on the status page (device / area) now properly link when they are compressed / hidden on mobile
> Update trs_status to use timestamps

- configs/config.ini.example
- mapadroid/madmin/routes/config.py
- mapadroid/utils/MappingManager.py
- mapadroid/utils/walkerArgs.py
Remove filewatcher and related config arguments from MAD.  This feature has been deprecated as the configuration has been moved to the database.
> Remove filewatcher

- mapadroid/madmin/routes/control.py
- mapadroid/mitm_receiver/MITMReceiver.py
- mapadroid/mitm_receiver/MitmMapper.py
- mapadroid/ocr/screenPath.py
- mapadroid/route/RouteManagerBase.py
- mapadroid/route/RouteManagerFactory.py
- mapadroid/utils/CustomTypes.py
- mapadroid/utils/MappingManager.py
- mapadroid/utils/collections.py
- mapadroid/utils/madGlobals.py
- mapadroid/utils/updater.py
- mapadroid/websocket/AbstractCommunicator.py
- mapadroid/websocket/WebsocketConnectedClientEntry.py
- mapadroid/websocket/WebsocketServer.py
- mapadroid/websocket/communicator.py
- mapadroid/worker/AbstractWorker.py
- mapadroid/worker/MITMBase.py
- mapadroid/worker/WorkerBase.py
- mapadroid/worker/WorkerConfigmode.py
- mapadroid/worker/WorkerFactory.py
- mapadroid/worker/WorkerMITM.py
- mapadroid/worker/WorkerQuests.py
- mapadroid/worker/WorkerType.py
- start.py
Since my original implementation of the websocket was a little confusing and wasteful, I kinda refactored it...
Meanwhile, I tried to add as much typing as I could (probably still missing some here and there, not too sure) and added a couple TODO comments.
Especially the handler of websocket connections has a TODO regarding cleanup, since we could reuse a running worker by just replacing the connection associated in the new WebsocketConnectedClientEntry-instance. We could, for example, add a method waiting for a new connection (with a timeout of e.g. one minute ofc to not get stuck forever) in case a WebsocketWorkerConnectionClosedException (new, raised when the connection to be used to send is not open anymore) is raised in a worker.
Also, I added AbstractWorker and AbstractCommunicator …
> Websocket rework

- mapadroid/patcher/__init__.py
- mapadroid/patcher/patch_25.py
- mapadroid/utils/apk_util.py
- scripts/SQL/rocketmap.sql
Fix for #719 
When a new MAD APK is uploaded it will not correctly clear out filestore_meta and filestore_chunks
> APK Database Cleanup

- mapadroid/data_manager/__init__.py
- mapadroid/data_manager/modules/resource.py
Fix for #726
Previously the default configuration was being updated vs cloned.  This caused unintended consequences where resources could not successfully be created or updated if the original one was deleted
> Clone the resource defition and defaults before modification

- mapadroid/worker/MITMBase.py
- mapadroid/worker/WorkerQuests.py
Update 2020-02-17:
Completely reworked and tested this. Should now handle the following, as described in the commit notes:
* fix #746: restart PoGo if clear tasks constantly fail
* fix #749: handle all WebsocketWorker* exceptions
* TODO: less magic numbers
* a little more logging for more info
* detect full quest log (FortSearchResultTypes.FULL)
* avoid softban deadlock by closing the stop after every spin attempt
* fix stops being silently skipped, handle timedelta issue better
* add GMO / 106 handling to _wait_data_worker (needed for spinnable check)
The goal is to increase efficiency and consistency of the quest scan mode by fixing a couple of issues and improving the overall working logic here and there.
Over a weekend of testing, I achieved more consistent scanning which translates …
> Quest fixes

- mapadroid/utils/updater.py
fixes #774. 
In analogy to mitm_receiver/PlayerStats.py, the JSON exception will be handled by deleting the file and showing an error message. https://github.com/Map-A-Droid/MAD/blob/0ceaa68a01dd85b8bf778ae91327c504d824b3c6/mapadroid/mitm_receiver/PlayerStats.py#L82-L84
Confirmed working by manually creating a `update_log.json` file containing invalid json.
> Fix 774: Handle corrupted update_log.json file

- mapadroid/worker/WorkerBase.py
Had a device endlessly loop with ScreenType.ERROR/ScreenType.FAILURE,
logging only: `[ WARNING] Something wrong with screendetection or pogo failure screen`.
It has to be assumed that `self._loginerrorcounter` somehow was incremented over 2, thus MAD was
unable to enter the appropriate routine because it only checked `self._loginerrorcounter == 2`.
I changed this to check `self._loginerrorcounter > 1` and to reset the loginerrorcounter to 0 once the routine ran to prevent this rare condition.
> Prevent rare loop with ScreenType.ERROR/FAILURE

- mapadroid/db/DbPogoProtoSubmit.py
#762 reports that the assigning of `spawnid` on line 103 throws an error when `str(wild_pokemon["spawnpoint_id"])` returns an empty string, because you cannot cast an empty string to a base 16 integer. This adds checking for that problem in the existing if condition that would return before the assignment of `spawnid` ever occurs.
I'm not a Python programmer so please let me know if my syntax can be improved for future commits. Hope this helps. Cheers!
> Resolution of #762

- mapadroid/db/DbWrapper.py
- static/madmin/static/js/madmin.js
`first_detection` is UTC, but MADmin showed it as if it's local time.
> Display spawn point first detection correctly.

- mapadroid/patcher/__init__.py
- mapadroid/patcher/patch_27.py
- scripts/SQL/rocketmap.sql
3 optimizations on `trs_spawn`:
* The two keys on `spawnpoint` are dropped and replaced with a single primary key.
* The column type of `spawnpoint` is aligned with `pokemon.spawnpoint_id` to increase join performance.
* Two additional keys are added to speed up some route and map related queries.
Changing a column type might affect 3rd party software, though it's not very likely. Rocketmap/Rocketmad seems to deal fine with those changes.
> Performance optimizations on trs_spawn & weather

- static/madmin/templates/statistics/shiny_statistics.html
Most of the people here uses it only too look for 'recent' mons. There is almost no reason to load everything every time. By default load mons from yesterday 00:00:00 to current date. Date picker still works.
Javascripts and dates - PITA.
> Load shiny mons only from midnight yesterday

- mapadroid/mitm_receiver/PlayerStats.py
`critical` is kinda overkill for a logline that everyone should ignore :P Maybe we can remove it completely?
> Change logging level of "no Statsfile found"

- mapadroid/route/RouteManagerBase.py
- mapadroid/utils/MappingManager.py
- mapadroid/worker/WorkerBase.py
- mapadroid/worker/WorkerMITM.py
... Thus a device will eventually restart pogo if it seems to be permanently stuck at a location. There have been reports from multiple users, me among them, of this happening.
MAD can't currently handle it because pogo doesn't freeze, so PogoDroid is still able to transmit related data, but from a wrong location.
Testing shows that a pogo restart seems to be enough to fix this.
> Cause a timeout if data received is too far away from intended scan location

- .dockerignore
Adds a `.dockerignore` file including the RGC APK which is part of the repository but not being used during build. 
This reduces the size of docker context during the build process, and it prevents that the APK eventually ends up in the final docker image.
> Add RGC APK to dockerignore

- static/madmin/templates/status.html
If we fail to get update 5 times in a row show alert with "Check browser console".
Could be anything - MAD restarting and request failing, connection issue, crappy 3G, anything.
> Silently ignore loading errors for few times in /status

- mapadroid/mitm_receiver/MITMDataProcessor.py
- mapadroid/worker/MITMBase.py
In my opinion, "Got the data requested" is the "actual success" of the scanner/worker we usually care about.
As argued on discord:
With the change, you'll basically get one SUCCESS or one WARNING (timeout) per route step on mon/raid scans (outside of unusual errors) instead of possibly multiple successes with data that's not relevant for the active scan mode. The changed output also makes sense in pokestop (quest) mode.
I think it's a logical change and makes it a little easier to see how your scanning is doing at a glance at the logs.
Got 2 agreements and no objections on discord, so I went ahead 😄
> Change SUCCESS logging

- mapadroid/data_manager/modules/area_pokestops.py
- mapadroid/db/DbWrapper.py
- mapadroid/geofence/geofenceHelper.py
- mapadroid/patcher/__init__.py
- mapadroid/patcher/patch_29.py
- mapadroid/route/RouteManagerBase.py
- mapadroid/route/RouteManagerFactory.py
- mapadroid/route/RouteManagerLevelingRoutefree.py
- mapadroid/utils/MappingManager.py
- mapadroid/worker/WorkerBase.py
- mapadroid/worker/WorkerQuests.py
- scripts/SQL/rocketmap.sql
Routefree Levelmode using near stops from db instand of generate a fix route.
**Usage**
Create big fence (Paris / Tokyo)
Create Area Pokestop with level:true
Setting Device Start position within this fence (Devicesettings) <-- not longer needed. MAD sets middle of fence as startposition
Let the magic beginn. 
**Activate routefree mode**
Create normal quest area with level = true and select route_calc_algorithm = routefree
> Integrate routefree levelmode in current master

- mapadroid/worker/WorkerQuests.py
pass will not stop code execution, it can crash if item_text is None due to tesseract crash.
Kinda mentioned in #813
> Fix a MAD crash when tesseract crash.

- mapadroid/madmin/routes/statistics.py
- static/madmin/templates/statistics/spawn_statistics.html
Loading mon_mitm by default, if you need anything else then just select from dropdown and wait again.
With a lot of areas and a lot of events this thing can takes aaaaaaaaaages to load. This way we can at least restrict it to one type of "geofence" and make it faster, a little.
> Dropdown filter for Spawnpoint Statistics

- mapadroid/db/DbWrapper.py
Doing any kind of calculation on an indexed column prevents MySQL
from using the index for queries.
So instead of
```
WHERE function(indexedcolumn) = expression
```
doing
```
WHERE indexedcolumn = inversefunction(expression)
```
can improve query performance in order of magnitudes.
> Fix SQL statement to use index instead of table scan

- mapadroid/patcher/__init__.py
- mapadroid/patcher/trs_status_lastProtoDateTime_fix.py
This update to the DB schema checks to see if the column lastProtoDateTime is updates each time the row is updated.  This field should only be updated when specified by the worker
> Fix for issue 756

- mapadroid/ocr/pogoWindows.py
- mapadroid/ocr/screenPath.py
- mapadroid/ocr/screen_type.py
- mapadroid/worker/WorkerBase.py
Propsing a few improvements to screendetection and related procedures. I tried to split the independent changes into separate commits so they could be used individually by the maintainers if they see it fit. I'll cite my commit notes as a summary here:
1. Detect GPS errors again
Due to false positives from heads up notifications, we ignored the upper
25% of the screen. Thus we also ignored red GPS errors in the game.
With this change, the upper 25% won't be ignored exclusively when checking
against the strings indicating GPS errors. This avoids the known false
positives from PogoDroid notifications while still being able to act on the
errors.
A slim chance for false positives remains, which could be handled by
disabling heads up notifications. They should be unnecessary on scanner
devices …
> Screendetection improvements

- mapadroid/ocr/screenPath.py
- mapadroid/worker/WorkerBase.py
As discussed with @cecpk -
this will do the following:
1. prevent a (seemingly rare?) loop on `screentype.LOGINSELECT` with PTC login by implementing more ways to find the PTC button - as it is done for the Google button already - by calculating the coordinates from other buttons.
2. significantly reduce the run time of `__handle_login_screen` using `elif` and `break` so the function exits after clicking one button instead of looping through all available boxes
3. using the opportunity to reduce the three warnings to one when pogo is not opened
> Improve login type selection

- mapadroid/mitm_receiver/MitmMapper.py
There's a rare exception where a location stat collection is attempted
with the current location being None. Checking for None before starting
the stat collection will prevent it.
> Prevent rare location NoneType exception

- mapadroid/worker/MITMBase.py
There seems to be a recent issue with clicks on the trash quest icon not
registering. This leads to the procedure not properly emptying the quest
bag, which in turn reduces efficiency of the quest scan mode because
stops will be spun when the quest bag is already completely filled. This
causes the need to re-visit the stop later.
It can be identified by this log line appearing in huge numbers:
`[ WARNING] Failed getting quest but got items - quest box is probably full. Start cleanup.`
This change significantly reduces occurence of the problem (90%+
reduction during my testing) at the cost of some more delay for these clicks.
It's more of a brute-force workaround than a pretty fix though. More
research into the exact problem should yield a more efficient solution.
> Workaround: Repeatedly click trash during quest deletion

- mapadroid/ocr/screenPath.py
- mapadroid/websocket/communicator.py
1) Identify the KO error from RGC as screentype.ERROR instead of getting wrongly caught as screentype.CLOSE in ``` elif "com.nianticlabs.pokemongo" not in topmost_app:```
2) fix #485 - on PTC the text below the green button on the failure screen needs to be clicked to be able to log in again. Independently found this issue and implemented the same fix @cecpk proposed in #485 .
I tested these for a couple of days, but cleaned them up today for the PR, so one or two tests or a couple more days in my setup would be good to 100% confirm them working.
> Handle KO error from RGC correctly, properly handle login failure on PTC

- mapadroid/data_manager/modules/routecalc.py
- mapadroid/route/routecalc/calculate_route_all.py
This PR creates a new file which will use the OR-Tools for routecalc's if it is available.  If not, it will return the original requested (quick/optimized) MAD routecalc.  I believe this will be a big benefit to MAD as the OR-Tools are very fast at calculating routes, and the length of the path found (for this test data) was always shorter than what MAD found.
Here are some runtime and route length comparisons I've run (all on a single core of my home computer) for various number of coordinates:
coords  mad   vs ortools :   mad_len  vs   or_len   : or_len/mad_len
50    1.5s vs   0.04s : 0.50242212 vs 0.50087158 : 0.996913
100   14.4s vs   0.22s : 0.54041637 vs 0.53329480 : 0.986822
150   26.4s vs   0.46s : 0.57627646 vs 0.57385556 : 0.995799
200   54.8s vs   0.96s : 0.69595905 vs …
> Add OR-Tools routecalc option

- static/madmin/static/style/MAD.css
Darkmode only, it was white on white, they were gone!
However not sure if mon/gym/spawn popup wasn't black earlier in darkmode and something changed?
> Force fa(s) icons to dark on leaflet popup

- static/madmin/templates/workerpicker.html
os is not mobile friendly to select anything. multi+shift is combo of shift+os, works on mobile, works almost the same as os without ctrl (shift still works). Win-win.
> Change select style to multi+shift

- mapadroid/ocr/pogoWindows.py
- mapadroid/ocr/screenPath.py
- mapadroid/ocr/screen_type.py
See title. Also:
+ remove the handling procedure that was wrongly implemented because
of this mix-up.
+ describe the ScreenTypes more clearly.
This is ScreenType.FAILURE - one green button saying OK. Obviously we want to click the button here:
This is ScreenType.RETRY - green button on top saying RETRY, clickable "non-button text" below saying "TRY A DIFFERENT ACCOUNT". We want to click the "non-button text":
Edit: Due to the nature of the issue - dealing with an error condition that has to pop up first - this is untested beyond making sure that MAD still starts.
> fix a mix-up of ScreenTypes FAILURE and RETRY

- mapadroid/worker/WorkerQuests.py
[07-03 10:55:56.97] [            atv03] [       WorkerQuests:267 ] [I] main: Walking 87.05069323933938 m, this will take 2.4871626639811253 seconds
[07-03 10:55:59.49] [           system] [  MITMDataProcessor:73  ] [I] Processing GMO received from atv03. Received at 2020-07-03 10:55:58
[07-03 10:56:05.49] [            atv03] [       WorkerQuests:310 ] [I] Timediff between now and last action time: 8
delay_used is compute with km/h and not m/s on walking code
No reel impact . Juste reduce  negative time wait :)
> Convert speed on km/h to m/s

- Dockerfile
Although being a dependency of python-opencv, libgl1 seems to be purged later in the Dockerfile, and therefore require explicit installation.
> Dockerfile: explicitely install libgl1

- mapadroid/data_manager/modules/device.py
- mapadroid/data_manager/modules/pogoauth.py
- mapadroid/mad_apk/utils.py
- mapadroid/madmin/api/autoconf/autoconfHandler.py
- mapadroid/madmin/api/autoconf/ftr_autoconf.py
- mapadroid/madmin/api/resources/resourceHandler.py
- mapadroid/madmin/madmin.py
- mapadroid/madmin/routes/autoconf.py
- mapadroid/madmin/routes/config.py
- mapadroid/tests/api/test_pogoauth.py
- mapadroid/tests/mad_apk/base_storage.py
- mapadroid/tests/mad_apk/test_wizard.py
- mapadroid/tests/test_autoconfig.py
- mapadroid/tests/test_utils.py
- mapadroid/utils/autoconfig.py
- static/madmin/templates/autoconfig_logs.html
- static/madmin/templates/autoconfig_pending.html
- static/madmin/templates/base.html
- static/madmin/templates/settings_singledevice.html
- static/madmin/templates/settings_singlepogoauth.html
UX Improvements for Auto-Config
* Viewing the log page for a session when completed or deleted now prompts an redirects to the pending page
* Add a warning message if no auth is configured
* Require MAD Packages to be up-to-date before a session can be accepted
* MADmin Packages must be available or a blocking issue will prevent auto-config from executing
* Allow a device to be added through the PogoAuth Page
* Only allow a Google PogoAuth account to be assigned to a single device
* Display a warning message on a device if autoconfig is required to have an assigned Pogo Auth and none is present
> AutoConfig UX Improvements

- mapadroid/data_manager/__init__.py
- mapadroid/data_manager/modules/device.py
- mapadroid/madmin/api/resources/ftr_device.py
- mapadroid/utils/MappingManager.py
- mapadroid/websocket/WebsocketServer.py
- mapadroid/worker/WorkerConfigmode.py
A paused device will now run under ConfigMode worker which allows it to stay connected to MAD. This replaced the old functionality of not allowing the device to reconnect.
Implementation for #923
> Pausing device enables ConfigMode for the worker

- static/madmin/templates/statistics/spawn_statistics.html
- static/madmin/templates/status.html
Some grammar, spelling, and formatting fixes within the madmin panel. 
Will be sad to see the smiley go. :( 
Kind of....
> Text fixes within madmin

- mapadroid/db/DbPogoProtoSubmit.py
- mapadroid/db/DbSchemaUpdater.py
- mapadroid/db/DbWebhookReader.py
- mapadroid/db/DbWrapper.py
- scripts/SQL/rocketmap.sql
This will add a new `evolution` column to the `raid` table. Default value is always "0" but keep in mind, that old raids in the DB may still be set to NULL. This will update over time.
Webhook notifications for raids include the `evolution` property as well.
> Add evolution/mega support

- mapadroid/mitm_receiver/MITMReceiver.py
- mapadroid/utils/walkerArgs.py
If MAD is not available, PD will perform several retries to send mitm
data to MAD. Due to recent changes in 0.185.0, the amount of data coming
in from the game grew quite a lot. This can cause issue for dozens of
devices filling up the queue without it being processed fast enough.
Either start MAD with `--mitm_ignore_pre_boot` / `-mipb` or just add
`mitm_ignore_pre_boot` without any value to your config.ini.
> add option to ignore backlog mitm data

- static/madmin/static/js/madmin.js
After #959 . We need workers to use them in Inject Location (right bottom corner, satellite dish icon) https://github.com/Map-A-Droid/MAD/blob/41047464753eba5612874bc70fdab1799f1b1d39/static/madmin/templates/map.html#L213 - without enabled workers layer list was empty. I don't think enabling workers here should kill performance (one more GETs), but maybe we want it 'on-demand' before opening Inject Location modal? @MrJul you decide, kinda nuking all this nice job of not requesting 175781785871578178 of GETs every few seconds :D
> Quick-fix for missing workers in Inject Location

- mapadroid/worker/MITMBase.py
I recently had a problem with a client where the logs showed:
```
[08-23 15:03:19.69] [           atv107] [  MITMDataProcessor:71  ] [I] Processing GMO received. Received at 2020-08-23 15:03:20
[08-23 15:03:29.77] [           atv107] [  MITMDataProcessor:71  ] [I] Processing GMO received. Received at 2020-08-23 15:03:30
[08-23 15:03:35.85] [           atv107] [           MITMBase:188 ] [W] Timeout waiting for data
[08-23 15:03:38.87] [           atv107] [           MITMBase:131 ] [I] Waiting for data after 2020-08-23 15:03:35.290276
[08-23 15:03:39.51] [           atv107] [  MITMDataProcessor:71  ] [I] Processing GMO received. Received at 2020-08-23 15:03:40
[08-23 15:03:39.88] [           atv107] [           MITMBase:174 ] [S] Got the data requested
[08-23 15:03:39.88] [ …
```
> Give more info about 'got the data requested'

- static/madmin/static/js/madmin.js
- static/madmin/templates/map.html
Fixed priority route nodes not having a popup after #959 (fixes #976).
Also added a popup on the route polyline itself, to match the normal route one.
> Prioq nodes now have a popup again. Added prioq line popup. Fixes #976

- static/madmin/static/js/leaflet-event-forwarder.js
- static/madmin/templates/map.html
Double clicking on the map while creating or editing a fence was adding two markers at the same location: the polygon became self-intersected, preventing further editing. It's fixed in leaflet-geoman 2.7.0, but the event forwarder was also messing with the fix.
> Fixed double clicking on map preventing fence creation/editing

- mapadroid/madmin/routes/statistics.py
But we lost the shinies of icons. I could not find a public repo with shiny icons :(
Also removed old, not used anywhere function + endpoint.
> Remove need of PogoAssets for shiny mons stats

- mapadroid/patcher/__init__.py
- mapadroid/patcher/pokemon_iv_index.py
- scripts/SQL/rocketmap.sql
- static/madmin/templates/statistics/mon_statistics.html
- static/madmin/templates/statistics/shiny_statistics.html
- static/madmin/templates/statistics/statistics.html
- static/madmin/templates/statistics/stop_quest_statistics.html
The mon statistics page took almost 8 seconds to load for me with 780k encounter rows in the db.
Here are the changes:
1. The recent 100% mons query was the main culprit. No indexes were used for this query: the one on `individual_attack` apparently wasn't sufficient. After adding on index on the 3 IV stats, the query is almost instant. I've also deleted the attack index since it's covered by the new one.
2. `pdfmake` has been updated; for some reason the older version was slow (hundreds of ms) to load.
3. Defered rendering has been enabled on DataTables: it avoid loading hundreds of mon images when only 10 rows are visible by default.
4. Images have a height to prevent row size from changing after the image is loaded.
TL;DR: 1s < 8s
> Optimized mon statistics page load

- static/madmin/static/js/madmin.js
`computed` properties were duplicated in `madmin.js` (probably by a recent merge)
> Removed map duplicate computed properties

- mapadroid/worker/WorkerQuests.py
This looks like a long string ("Remote Raid Pass") does not really match short strings provided ("Remote", "Raid"). Plus the premium was renamed to "Battle" pass long time ago and with nice OCR it was still trying to delete it.
```
0.1 for Gift vs Remote Raid Pass
0.16666666666666666 for Geschenk vs Remote Raid Pass
0.08333333333333333 for Glücksei vs Remote Raid Pass
0.08 for Glucks-Ei vs Remote Raid Pass
0.08 for Glücks-Ei vs Remote Raid Pass
0.08 for Lucky Egg vs Remote Raid Pass
0.14814814814814814 for CEuf Chance vs Remote Raid Pass
0.2727272727272727 for Cadeau vs Remote Raid Pass
0.2 for Appareil photo vs Remote Raid Pass
0.08 for Wunderbox vs Remote Raid Pass
0.2222222222222222 for Mystery Box vs Remote Raid Pass
0.3448275862068966 for Boîte Mystère vs Remote Raid Pass …
```
> Add more variations of Remote Raid Pass/Premium Battle Pass

- mapadroid/data_manager/modules/device.py
- mapadroid/data_manager/modules/pogoauth.py
- mapadroid/data_manager/modules/resource.py
- mapadroid/madmin/api/autoconf/ftr_autoconf.py
- mapadroid/madmin/routes/autoconf.py
- mapadroid/madmin/routes/config.py
- mapadroid/mitm_receiver/MITMReceiver.py
- mapadroid/ocr/screenPath.py
- mapadroid/patcher/__init__.py
- mapadroid/patcher/move_ptc_accounts.py
- mapadroid/tests/api/test_device.py
- mapadroid/tests/api/test_pogoauth.py
- mapadroid/tests/test_autoconfig.py
- mapadroid/utils/MappingManager.py
- mapadroid/utils/autoconfig.py
- scripts/SQL/rocketmap.sql
- static/madmin/templates/settings_pogoauth.html
- static/madmin/templates/settings_singledevice.html
- static/madmin/templates/settings_singlepogoauth.html
Implement PTC accounts to be used as PogoAuth credentials. Moved existing PTC accounts (ptc_login) into PogoAuth and auto-assigned to the device. This change also fixes #775 as the character limit is now 128 for the usesername and password (separately) and not tied to the device.
> Implement PTC as PogoAuth

- mapadroid/data_manager/modules/resource.py
- mapadroid/data_manager/resource_search.py
- mapadroid/patcher/move_ptc_accounts.py
- requirements.txt
* Fixed an issue where conversion would not apply the correct instance_id to ptc accounts being converted
* Implemented additional search functionality within the data manager (.eq and .like)
* PogoAuth accounts are now pulled correctly with the search functionality update
* Updated requirements.txt to not use greenlet 0.4.17 as it caused issues with py3.7
> PTC / Data Manager fixes

- static/madmin/static/js/madmin.js
It's deprecated for 3rd parties, and use will be disallowed in the near future (slated for 2020-10-12; ie tomorrow as of writing)
https://lists.wikimedia.org/pipermail/maps-l/2020-August/001729.html
https://phabricator.wikimedia.org/T261424
> Remove Wikimedia tileserver from maptiles

- mapadroid/webhook/webhookworker.py
As proposed in #1023, some of the global webhook parameters are going away. 
The changes from #1023 may cause performance issues if one only wants to send raids (by using filters). This PR builds a list of types and only fetches data for these types similar to the old parameters. 
If there's no filter, MAD will automatically generate a list of all possible types.
> Rework webhook worker to fetch only data for filtered types

- mapadroid/worker/WorkerQuests.py
You can now click Stickers in inventory and it will open page full of stickers.
There is no trashcan on those stickers in main menu (for now, I can imagine Niantic QoL update).
Can't really get names in French/German, not translated in PokeMiners assets, will update later (or someone can comment).
> Add Stickers to not deletable items

- mapadroid/utils/s2Helper.py
Helper method could return the wrong s2 cell in some edge cases because we used regioncoverer methods with a point area given coordinates instead of points
> Fix lat_long_to_cell_id

- mapadroid/ocr/pogoWindows.py
cv2.imwrite will silently fail if it can't save image (for example due to permissions). It will not throw any error, just False/True as return.
Let's handle it, so next guy will waste less time on debugging
> Message error when can't save file to temp_path

- mapadroid/db/DbPogoProtoSubmit.py
- mapadroid/mitm_receiver/SerializedMitmDataProcessor.py
- mapadroid/utils/gamemechanicutil.py
In edge cases and/or during a data processing queue backlog, it can happen that a Pokemon will be scanned on the device, but only processed in MAD after it already has despawned.
In that case, the Pokemon would be wrongly stored to database as despawning one hour later, because the processing takes `now()` as the starting point for the despawn calculation.
This PR changes that behaviour so that the actual timestamp of the submitted proto data is used as the starting point instead of `now()`, thus ensuring that a despawn in the "now-past" will still be correctly calculated.
> Calculate despawn time from data timestamp instead of now()

- mapadroid/data_manager/modules/area.py
- mapadroid/tests/api/test_area.py
This should be a proper place to put it, I guess.
I would assume we don't really need to check if mode is `pokestops` due to `level` being only in pokestops thing
> Warning message when trying to run init and level

- mapadroid/worker/WorkerBase.py
A little collection of small changes I made to WorkerBase and successfully tested on my setups over the last couple of weeks.
1. There are situations where `_ensure_pogo_topmost` can return without having accomplished the purpose its name indicates - imo it should truthfully return `False` in a case like that
1. There is a silent eternal loop in `_start_pogo` - if RGC is, for whatever reason (usually weird system freezes) permanently unable to launch pogo but still responding to MAD, it'll forever loop sleeping 1s, then trying to start pogo again, without any log output. Fixed by adding a counter + threshold and returning `False` upon reaching the threshold.
1. A failure of restarting pogo should not happen under normal circumstances and thus indicates an issue with the device, like …
> WorkerBase fixes

- mapadroid/db/DbWrapper.py
scannedlocation was off by default and now it's on by default. People will old af databases schema has some strange CONSTRAINTS there, so let's just quickfix value from -1 to 0 before final decision what to do.
https://discord.com/channels/465247740553592832/467318193141317659/768947899748843591
> QuickFix for scanned location

- mapadroid/mitm_receiver/SerializedMitmDataProcessor.py
This PR enhances debug2 (`-vvv`) logging for data processing. It adds times in milliseconds for each data type and even each sub type (gyms, stops, mons etc) for GMOs. May help finding bottlenecks in DB performance.
Real world example with actual timings for a mon_mitm scanner:
> [11-04 16:07:29.59] [           device] [SerializedMitmDataProcessor:84  ] [D] Done processing GMO in 39ms (weather=2ms, stops=6ms, gyms=8ms, raids=7ms, spawnpoints=5ms, mons=2ms, cells=7ms, gmo_loc=1ms)
For log/stdout grepping, you can either grep for the `SerializedMitmDataProcessor` to get a general logging overview for processed data, or grep for `Done processing` to only get actual timings.
As an extra, processing queue items will produce another log line
Demo example:
> MITM data processor …
> Add debug logging for data processing times

- mapadroid/mad_apk/apk_storage_fs.py
- mapadroid/mad_apk/utils.py
- mapadroid/mad_apk/wizard.py
- mapadroid/tests/mad_apk/test_wizard.py
Validates returned version code against requested version code
> Wizard validation

- mapadroid/db/DbWrapper.py
Raids were not showing on madmin maps if local timezone was before GMT/UTC (-), was working when it was after, +.
@Expl0dingBanana can you check if this thing also works on your strange UTC everywhere setup?
> Timezones fix

- locale/de/items.json
- locale/en/items.json
- locale/fr/items.json
- scripts/parse_items_for_items_json.py
It fixes some names, adds some missing items but it also adds items that are defined in protos, but do not have a name in lang files - so in theory not implemented(?) in-game. It uses theirs protoname for name there. In theory we could skip those if you guys want, but that is @fosJoddie decision I guess :D
Plus add a script that parses Furtif/POGOProtos and Poke_Miners in-game language files for future use, so no more copy-pasting if they put new things in, maybe.
> Add missing items names to items.json (and langs)

- mapadroid/route/RouteManagerBase.py
Splitting a route into subroutes is now fairer when the number of locations isn't divisible by the worker count. The old algorithm was making the last subroute shorter than the others.
Example: 212 locations, 5 workers
Before: 4×43 + 1×40
After:  2×43 + 3×42
Also adjusted the logging to display the number of workers (worker details are already logged a few lines later).
> Fairer route splitting into subroutes

- mapadroid/db/DbStatsReader.py
- mapadroid/madmin/routes/statistics.py
- static/madmin/templates/statistics/mon_statistics.html
This should add heatmap of non-IV's encounters at the end of Statistics -> Mon Stats. This should help visualize where IV's are not getting checked enough and it's probably worth to add one more worker. This uses 4 hour window (by default, not configurable at this point, yet it's semi-ready) - please do check if after 4 hours of normal mon work (so don't try to check it in middle of questing at 4:00 am - it won't really show anything useful).
By default it will show location with 2+ times no IV checked at coords, slider should allow you to adjust how many non-IV encounters per spawn you want to see. You can in theory lower the slider back to 1 non-IV encounter but this will probably produce a lot of points and won't be useful.
I need someone with a lot (A LOT) of data to test it please - …
> Heatmap of non-IV's encounter

- mapadroid/worker/WorkerQuests.py
Lately there were several scattered reports of devices behaving weirdly and getting stuck in a constant loop of the loglines `Can't spin stop - no map info in GMO!` and/or `Can't spin stop - couldn't find it closeby!`.
The devices would be stuck trying to click or spin stops and receiving a pink `Try again later` warning, or walking from stop to stop without interacting with them.
This indicates some sort of obscure issue(s) retrieving GMO data correctly containing the desired PokeStop. As also the game itself indicates an issue with the pink warning popping up, it seems a restart of the game app would be in place if this behaviour is shown persistently.
The number of 10 consecutive failed checks to trigger a restart was chosen arbitrarily. 🤷‍♂️
> Count up and restart on repeated spinnable check failures

- mapadroid/db/DbWrapper.py
- mapadroid/mitm_receiver/MitmMapper.py
- mapadroid/route/RouteManagerQuests.py
- mapadroid/utils/ProtoIdentifier.py
- mapadroid/utils/gamemechanicutil.py
- mapadroid/worker/MITMBase.py
- mapadroid/worker/WorkerBase.py
- mapadroid/worker/WorkerMITM.py
- mapadroid/worker/WorkerQuests.py
- static/madmin/templates/quests.html
Title sorta says it all
I thought it was time to add some typing to the wait_for_data routine and sort it out a little at least.
While I was at it, I adjusted the location checks to be purely based on what the data sent to MAD holds as lat/lon.
Additionally, the `maximum_valid_distance` config argument will now actually take effect.
> Tidy up wait for data

- .isort.cfg
- Makefile
- docker/Dockerfile-dev
An issue was occurring where MacOS refused to build / run tests due to UID issues. This PR addresses those UID issues and optimizes the build for the development environment by reducing the layers and modifying some commands.
> Update dev build to better support multi-os

- mapadroid/utils/pluginBase.py
Fixing two issues:
* previously, unhandled exceptions caused by faulty plugins would stop loading subsequent plugins, now it'll be visible which plugin caused issues and why, and we'll be able to continue with subsequent plugins
* recursing into hidden directories caused an exception because the contruction of package names as `package + '.' + child_pkg` with child_pkg starting with a dot seems to have caused invalid package names. There should be no reason to recurse into directories that are hidden / starting with a dot.
Found, applied and tested somewhat extensively during development of my recent poracle pvp plugin.
Running several other private and public plugins with these changes applied without problems.
> plugins: handle exceptions in walk_package, ignore hidden directories

- Makefile
- docker/.dev.env
- docker/docker-compose-test.yaml
- mapadroid/worker/WorkerQuests.py
This PR allows for a persistent testing environment between runs. This is helpful when you are doing testing and the containers are going offline.
* Add a command to run the test environment
* Added a new docker-compose file, docker-compose-test, that maintains a Persistent MariaDB database
> Persistent testing env

- .github/workflows/tox_testing.yml
- docker/docker-compose-dev.yaml
- mapadroid/data_manager/__init__.py
- mapadroid/data_manager/modules/resource.py
- tests/data_manager/test_core.py
- tests/data_manager/test_resource_tracker.py
- tests/fixtures/fixture_data_manager.py
- tests/fixtures/fixture_db_wrapper.py
- tox.ini
* Converted the ResourceTracker into pure python functions to allow ease-of-use for Unit-Testing.
* Added mocking for the base fixtures. Using the actual connections is still available (_real)
* Added the action, tox-gh-actions. This will be used when we migrate off travis to GH Actions
> Unit-tests for the ResourceTracker / Data Manager

- .git-blame-ignore-revs
- static/madmin/templates/upload.html
- static/madmin/templates/uploaded_files.html
Fixed a regression where the delete button no longer appeared for uploaded APKs. This bug was created during #932 when the name changed from "jobType" to "JobType" 
Updated the file-browser to default to *.apk files as they are the only extensions accepted (.txt is accepted too but i don't see how that is beneficial here...)
> Restore delete button

- mapadroid/mad_apk/wizard.py
- mapadroid/tests/mad_apk/test_wizard.py
1. Make the Wizard "Update Everything" do the filesize check for RGC/PD before downloading (this check is run when clicking the "Search for new version" button in the individual lines above).
2. Improve the pogo update logic to make the logging easier to understand and to enable it to download "intermediate" versions. Example: `195.0` is installed. `195.1` is available to be downloaded through gplay. `195.0`, `195.1` and `195.2` are supported via the `version_codes.json` file. Previously, downloading `195.1` in this situation was not possible while `195.2` was not yet available through the store, thus we would remain at `195.0`. This behaviour should be fixed.
3. Fix a wrong global variable reference (was `VERSIONCODES_GITHUB`, corrected to `VERSIONCODES_URL`)
@Expl0dingBanana - please …
> Wizard fixes

- requirements.txt
There seems to be 1.0 release that breaks a lot of stuff and makes MAD go haywire.
> Force greenlet to < 0.4.17

- mapadroid/mad_apk/wizard.py
The issue was brought up on discord and is caused by changes from PR #1081.
A `TypeError` exception was thrown when trying to download RGC or PD through the wizard with no pre-existing version on the MAD instance. I could reproduce the problem locally and fix it with these changes.
It was not considered that the packages variable could be `None` when no version of the requested package is currently installed to
the MAD instance. This commit/PR will introduce code to handle this situation.
> Fix a TypeError exception in __find_latest_head in wizard.py

- mapadroid/db/PooledQueryExecutor.py
- mapadroid/madmin/api/apiHandler.py
- mapadroid/madmin/api/apks/ftr_mad_apks.py
- mapadroid/madmin/madmin.py
- mapadroid/route/RouteManagerIV.py
- mapadroid/route/RouteManagerLeveling.py
- mapadroid/route/RouteManagerLevelingRoutefree.py
- mapadroid/route/RouteManagerMon.py
- mapadroid/route/RouteManagerQuests.py
- mapadroid/route/RouteManagerRaids.py
- mapadroid/utils/logging.py
- mapadroid/utils/updater.py
- mapadroid/worker/MITMBase.py
- mapadroid/worker/WorkerMITM.py
- mapadroid/worker/WorkerQuests.py
Changes in a nutshell:
- Locks (not Semaphores - which we have some still) are now used via `with` rather than try-finally
- "unhanded exception" -> "unhandled exception"
- WorkerQuests::_try_to_open_pokestop now returns an enum as we had a Tuple[bool, bool] before which imho would not properly cover the permutations of results possible
- MITMBase::_wait_for_data now cuts off the decimal places of the timestamp passed as PD uses integers (long) values thus sometimes resulting in MAD waiting for data that was received before the timestamp used by MAD internally (being float)
> Pythonic locking

- docker/Dockerfile
Include the Python redis package for optional usage. As redis is only activated when the flag is set in config it will not automatically load the package. Ensuring its install allows redis usage in a dockerized environment.
> Include redis package as optional dependency for Docker

- mapadroid/webhook/webhookworker.py
Using index instead of rindex finds the first closing bracket and not the one of the IPv6 adress.
> IPv6 support for webhooks

- static/madmin/templates/statistics/spawn_details.html
Rename columns: Last scanned to Last despawn time confirmation; add new "Last mon scanned"
Truncate GPS coords to 8 chars (you can still search by full coords, this is only display thing) - I'd rather see last mon seen time rather than full 18 chars long GPS coords
Drop that strange Date() thing - I don't think we really need moment.js here for spawn times overview, this should be enough
Drop that saving to localstrorage that cec uses everywhere when we don't need it at all. This:
```
"stateSave": true,
"stateDuration": 0
```
take cares of everything.
This is #941 but github webui to resolve conflicts made a mess so it was easier to just re-do.
> rearrange spawn details from spawn statistics

- mapadroid/db/DbPogoProtoSubmit.py
- mapadroid/db/DbWebhookReader.py
- mapadroid/db/DbWrapper.py
- mapadroid/patcher/__init__.py
- mapadroid/patcher/add_is_ar_scan_eligible.py
- mapadroid/utils/questGen.py
- mapadroid/webhook/webhookworker.py
- scripts/SQL/rocketmap.sql
This is totally useless now, nothing supports this, but could be useful in future.
gyms & quests webhook uses that flag. We don't have webhook for pokestop changes (and that would need a lot of logic), so I ended up and put that in quests - once day, should be good enough.
> Add is_ar_scan_eligible flag to pokestop and gyms

- mapadroid/mitm_receiver/SerializedMitmDataProcessor.py
- mapadroid/utils/walkerArgs.py
On some setups, the queue of mitm data grows for unknown reason. To compensate this issue, users started to add automatic restarts to cleanup said queue.
This PR adds a new parameter `mitm_ignore_proc_time_thresh` (`miptt`) which let's users configure a threshold in seconds to ignore these payloads within the queue. 
Payloads are still being added to the payload but once they're about to be processed the timestamp is being checked and depending on the threshold ignored. Some payloads may still have a (huge) time difference due to miscofigured date/time on the device or bad connection between device and server.
> add threshold to ignore mitm data in queue

- mapadroid/db/DbWrapper.py
Every time a worker switches to IV scan, it wants to update PD with the encounters stored in the `pokemon` since the last scan. However, if that happens on the first connect, the last-scan timestamp is `0`. This causes a full table scan on `pokemon` which - depending on the number of mons stored, can take quite some time and could return a huge amount of data.
To avoid this condition, we simply fetch the last 15 minutes in those circumstances.
> Avoid full scan of pokemon table when worker starts for IV scan

- Makefile
- docker/.dev.env
- docker/docker-compose-persistent.yaml
- docker/docker-compose-test.yaml
- mapadroid/madmin/api/autoconf/ftr_autoconf.py
- mapadroid/tests/test_autoconfig.py
- mapadroid/utils/autoconfig.py
Enables AutoConfig / Origin Hopper to use PTC accounts if they are available during auto-config.
Fix for #1111
> PTC Autoconfig support

- mapadroid/data_manager/modules/routecalc.py
- mapadroid/madmin/routes/map.py
- mapadroid/route/RouteManagerBase.py
- mapadroid/utils/MappingManager.py
- static/madmin/static/js/madmin.js
- static/madmin/static/style/madmin.css
- static/madmin/templates/map.html
With this PR, `mon_mitm` routes can now be edited.
It's based on the geofence editor and works the same (click on a route, choose *edit* in the popup, drag/add/remove points, click *save* in the popup): common code for the two editors has been extracted.
Once edited, a route won't be active in memory until settings are applied. The main problem here is that refreshing the map without applying settings would get back the "old" applied/unedited route from memory. To avoid this, the map now shows an additional "unapplied" route. 
To avoid confusion, there are several special rules regarding this unapplied route:
- It only exists if it's different from the applied route (= the route has been edited)
- After saving, the edited/unapplied route is automatically made visible and the applied route …
> Implemented route editor. Fixes #1057

- mapadroid/db/DbWrapper.py
We need str here - all other checks are against strings and delete query expects string.
Nothing else call this except mentioned function so we can just force string here :)
> Fix `Delete all unfenced spawnpoints`

- mapadroid/webhook/webhookworker.py
The existing loglevel warning message is not all too helpful when serving more than one webhook destination.
With this change, you'll be able to know which destination is having issues.
> Log webhook destination when HTML response not 200

- mapadroid/utils/autoconfig.py
This should fix this error:
```
[03-28 23:27:44.25] [           system] [PooledQueryExecutor:126 ] [E] Failed executing query: SELECT *
FROM `settings_pogoauth` ag
WHERE ag.`instance_id` = %s AND ag.`device_id` IS NULLAND ag.`login_type` = %s ([1, 'ptc']), error: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'NULLAND ag.`login_type` = 'ptc'' at line 3
```
> Fix a missing space in an autoconfig query

- static/madmin/static/js/madmin.js
- static/madmin/templates/map.html
If at anytime while dragging fence or route points both mouse buttons are pressed, leaflet sends a second drag start event but still only drag end and the map input is blocked. While waiting for the double event to be fixed, here's a simple workaround.
> Fixed fence/route editor not being clickable anymore in some cases

- mapadroid/ocr/screenPath.py
- mapadroid/ocr/screen_type.py
- mapadroid/worker/WorkerBase.py
A system popup about an app not responding blocks most if not all actions of MAD / RGC on a device. It's also usually a symptom of the affected system having severe issues. A instant reboot is therefore usually the correct and quickest solution.
> Handle "<app> isn't responding" system popup

- mapadroid/ocr/screenPath.py
- mapadroid/worker/WorkerBase.py
For whatever reason, on some devices, a `ConsentActivity` screen appears after logging into a Google account. MAD was able to detect this screen, but couldn't handle it yet. 
The content is not readable via uiautomator due to it being a webview. I might've missed it, but we don't have a general OCR method that finds certain text and and its position on the screen to properly find the "Allow" button's position. On some screen resolutions we might even have to scroll down first.
For now, this should "fix" the consent screen on the x96 mini running the 64bit MAD rom.
> handle google's consent screen for 720p displays

- requirements.txt
Probally not worth to checkout 2.0.0 before Grenn rework :)
> Pin Flask to 1.1.4, 2.0.0 nuked some things.

- mapadroid/worker/WorkerQuests.py
There was a log line in WorkerQuests.py with placeholders missing their variables. I added what I assumed to be intended in there.
> Minor text fix

- requirements.txt
0.8.4 is broken, 0.9.0 is supposed to be working (Discord feedback), 0.10.0 is supposed to be broken too. Let's just stick to known-working-version.
> Pin apkutils to 0.8.3

- mapadroid/data_manager/modules/device.py
Something somewhere is broken, happen like 3 times last week on Discord.
No free device to test what and where is broken, just 'hotfix' for now.
> Disallow space in origin when creating device.

- mapadroid/ocr/screenPath.py
From time to time people will show up in Discord with configured PTC account in AutoConfig and leaving `logintype` as default aka Google and asking why it's not working. With one more log line there is a chance they will figure it out earlier why and how.
Added (f), (c), etc. to log which was condition was found, just because we can.
> Screenpath log what loginbutton/type we supposed to click

- configs/config.ini.example
- mapadroid/data_manager/modules/area_mon_mitm.py
- mapadroid/db/DbPogoProtoSubmit.py
- mapadroid/utils/gamemechanicutil.py
- mapadroid/utils/walkerArgs.py
- mapadroid/webhook/webhookworker.py
This adds some more fixes to my PR #1120 as well as new config options.
config options
- disable_nearby_cell - disables nearby_cell pokemon if nearby scanning is activated
- default_nearby_timeleft - default minutes left for nearbies
- default_unknown_timeleft - default minutes left for wilds/encounters at unknown spawnpoints
webhook fixes (thanks jab):
- ipv6 support
- properly handle pokemon -> encounter backwards-compatibility
> Fixes/improvements for #1120

- mapadroid/patcher/add_is_ar_scan_eligible.py
- mapadroid/patcher/dynamic_iv_list.py
- mapadroid/patcher/extend_trs_quest_pogodroid_190.py
- mapadroid/patcher/madrom_autoconfig.py
- mapadroid/patcher/more_ways_to_scan_mons.py
- mapadroid/patcher/patch_23.py
- mapadroid/patcher/patch_24.py
- mapadroid/patcher/patch_28.py
- mapadroid/patcher/patch_29.py
- mapadroid/patcher/reset_routecalc_algo.py
- mapadroid/patcher/routecalc_rename.py
Looks like we failed with copy-pasting code -> s/raise_exec/raise_exc/
I think I fixed all so next time we copy-paste it will be good 🥇 
This also did not stop some migrations in past, but seems they never failed up to now :-)
> Fix a typo in patchers and more info about more info about mon migration being long

- scripts/SQL/rocketmap.sql
This should have been part of #1120 but for whatever reason it didn't go in. This change is already part of #1120's DB patch.
[Banana's message confirming this was an accidental copy-paste](https://discord.com/channels/465247740553592832/562515411149651983/826029130222141471)
> remove encounter_id from pokestop

- mapadroid/utils/questGen.py
Looks like Niantic finally added megas to that.
```
'goal': {
'condition': [{
'type': 7,
'with_raid_level': {
'raid_level': [3, 4, 5, 6]
}
}, {
'type': 6,
'with_win_raid_status': {}
}],
'target': 1
},
```
> Fix `Win a level X or higher raid` quest

- mapadroid/db/DbPogoProtoSubmit.py
- mapadroid/db/PooledQueryExecutor.py
As suggested by Gren on discord, 'if not args: return none'
This prevents creating a connection to the database when the args variable is empty.
This should save some system resources by stopping unnecessary connections to the db.
Thanks to comstud for tracking this down and suggesting a fix.
> Don't connect to db for empty transactions

- mapadroid/route/RouteManagerBase.py
- mapadroid/route/RouteManagerIV.py
- mapadroid/route/RouteManagerMon.py
This refactors get_next_location() for the following purposes:
1) Remove recursion as it can deadlock. (See below.)
2) Don't sleep while holding a lock (happens currently for 'iv_mitm')
3) Don't pass coords for 'iv_mitm' as they are never used/looked at.
(See below.)
4) Remove checks on 'mode'. The base class should not have to have
different logic based on 'mode'. Mode specific logic should exist
in their respective classes!
More details:
* Issue 1 above: iv_mitm deadlocking
There are a few checks within the prioq section of get_next_location()
that can cause recursion. When this happens, a deadlock can occur.
This is due to the recursing of get_next_location() while holding
self._manager_mutex in combination with this loop that is at the top
of get_next_location() that loops until there …
> Fix iv_mitm deadlocking and other issues

- mapadroid/websocket/WebsocketServer.py
- mapadroid/worker/WorkerBase.py
Often in our setup, RGC reconnects before MAD notices that the old
connection is dead. When this happens, the worker is found to still
be running and not shutting down... thus the new connection is just
replaced in the WebsocketConnectedClientEntry for the worker to use.
However, once MAD finally detects the old connection is dead, it then
stops the worker... leaving no worker running for the new RGC
connection. The new RGC connection continues to ping/pong just fine,
but it's doing nothing else.. You have to restart the device (or MAD)
to recover from this.
This fixes the issue by moving the stopping of the worker to the
connection handler and only doing it when the 'Done' connection is
still the one in the WebsocketConnectedClientEntry.
But we also need to not allow new connections …
> Fix websocket/worker races

- .github/workflows/publish.yml
Docker Hub does not like its users, so we're switching to the better and faster GitHub registry .
> github action to build and host the docker image

- Dockerfile
- docker/Dockerfile-dev
Debian 11 (bullseye) changes apt packet name for opencv to python3-opencv.
It also comes with tesseract so I'm trying to see if this can be fetched directly instead
> WIP Make Dockerfile work again

- Dockerfile
At least with the current code libSM6 is a hard dependency:
```
Traceback (most recent call last):
File "start.py", line 19, in <module>
from mapadroid.madmin.madmin import MADmin
File "/usr/src/app/mapadroid/madmin/madmin.py", line 14, in <module>
from mapadroid.madmin.routes.control import MADminControl
File "/usr/src/app/mapadroid/madmin/routes/control.py", line 24, in <module>
from mapadroid.websocket.WebsocketServer import WebsocketServer
File "/usr/src/app/mapadroid/websocket/WebsocketServer.py", line 14, in <module>
from mapadroid.ocr.pogoWindows import PogoWindows
File "/usr/src/app/mapadroid/ocr/pogoWindows.py", line 8, in <module>
import cv2
File "/usr/local/lib/python3.7/site-packages/cv2/__init__.py", line 5, in <module>
from .cv2 import *
ImportError: libSM.so.6: cannot open …
```
> Add back OpenCV dependencies

- mapadroid/route/RouteManagerBase.py
- mapadroid/route/RouteManagerLeveling.py
- mapadroid/route/RouteManagerLevelingRoutefree.py
'with a and b:' does not do what one might think. The correct
syntax is 'with a, b:' or 'with a as foo, b as bar:', etc.
It seems that 'with a and b:' does require that 'a' have an
__enter__ method, but it never calls it... it just skips to 'b'
as can be seen below.
Additionally, had both locks worked, there was a lock ordering problem
in one spot.
```
class Testing:
def __enter__(self):
print('    enter: %s' % self.__class__)
return 1
def __exit__(self, a, b, c):
print('    exit: %s' % self.__class__)
class Testing1(Testing):
pass
class Testing2(Testing):
pass
t1 = Testing1()
t2 = Testing2()
print('testing with "and":')
with t1 and t2:
print('woot')
print()
print('testing with comma:')
with t1, t2:
print('woot')
----- OUTPUT ------
testing with "and":
enter: <class '__main__.Testing2'> …
```
> Fix route manager locking

- configs/config.ini.example
- mapadroid/mad_apk/__init__.py
- mapadroid/mad_apk/abstract_apk_storage.py
- mapadroid/mad_apk/apk_storage_db.py
- mapadroid/mad_apk/apk_storage_fs.py
- mapadroid/mad_apk/utils.py
- mapadroid/mad_apk/wizard.py
- mapadroid/madmin/api/apks/ftr_mad_apks.py
- mapadroid/madmin/routes/apks.py
- mapadroid/mitm_receiver/MITMReceiver.py
- mapadroid/utils/functions.py
- mapadroid/utils/global_variables.py
- mapadroid/utils/updater.py
- mapadroid/utils/walkerArgs.py
- requirements-test.txt
- static/madmin/templates/madmin_apk_root.html
- tests/fixtures/fixture_wizard.py
- tests/mad_apk/test_wizard.py
The supported versions is now dependant on MADdevs third-party
entrypoint. This enables the wizard to download the latest
supported version without relying on version_codes.json
* Add a new configuration option, maddev_api_token
* Update the wizard to query the MADdev endpoint with the token
> (feat)[wizard]: Supported versions from MADdev backend

- mapadroid/worker/MITMBase.py
Tested change described in issue 1102 by increasing WAIT_FOR_DATA_NEXT_ROUND_SLEEP from 0.5s to 1s. This has reduced my CPU usage by about 20%.
This worked for Dkmur's large setup and my setup of 35 devices.
I have not identified any negative impact.
Co-Authored-By: dkmur <42545952+dkmur@users.noreply.github.com>
> Increase Round Duration from 0.5s to 1s

- mapadroid/db/DbPogoProtoSubmit.py
- mapadroid/webhook/webhookworker.py
Currently all 'is_in_battle' values from gyms are set to false, even when being attacked
> Fix 'is_in_battle' status from gyms and add it to webhook requests

- mapadroid/utils/logging.py
- With the previous logic all standard logging logs are downgraded to
DEBUG5 regardless of their initial level. This will hide any fatal
errors making debugging harder.
- Since Werkzeug is quite chatty at INFO level, anything at INFO or
below is still downgraded to DEBUG5. This maintains the current
behavior for those log messages.
> Surface Werkzeug and other internal logging to loguru at orig level

- mapadroid/worker/WorkerQuests.py
This is a general safeguard against issues in QuestWorker that can cause infinite loops in MAD through device-side issues that don't go away by themselves (unable to open pokestops, unable to clear quests). It'll restart the app on these occasions.
Specifically there's lots of reports in discord that this works around issues with Pokestops not loading on PoGo 229.x+ with latest PD.
> Add more failcounts to quest worker

- mapadroid/webhook/webhookworker.py
There is currently a conflict with the webhook worker when switching from `default` to `poracle` `quest_webhook_flavor` setting.
The `poracle` quest flavor removes a lot of default fields instead of adding the ones which need to be added. This causes the webhook sent to PokeAlarm to be invalid as some mandatory fields are missing.
- Default quest webhook sent: https://github.com/Map-A-Droid/MAD/blob/543c3d7f002cdb64f2b6209d450ec18adc905a85/mapadroid/webhook/webhookworker.py#L154
- Poracle quest webhook sent: https://github.com/Map-A-Droid/MAD/blob/543c3d7f002cdb64f2b6209d450ec18adc905a85/mapadroid/webhook/webhookworker.py#L296
All the quest fields added for `poracle` flavor are compatible for both PokeAlarm and PoracleJS as they don't use the same name and so, they don't overwrite any …
> Add missing pokealarm fields in quest webhook when using poracle flavor

- mapadroid/worker/strategy/quest/QuestStrategy.py
If it is found that a pokestop reports as on cooldown, 
we assume we must have the info about it and treat it as ok
> Accept pokestop cooldown as spun

- mapadroid/webhook/webhookworker.py
Was not sending pokemons if you had something like `webhook_url: http://127.0.0.1/` - no `[type, type, type]` specified.
> Fix pokemon missing from webhook if no type specified

- mapadroid/madmin/endpoints/routes/control/DeleteLogEndpoint.py
wrong keyword used
Personally I would love one more brackets there so my brain could process it :D 
` await self._get_device_updater().delete_log(only_success=(only_success and only_success.lower() == "true"))`
> Fix deleting Job logs

- mapadroid/db/helper/RaidHelper.py
Raid PrioQ was prioritizing hatched raids that were already scanned. Correct it to prioritize hatched raids that are still unknown.
> Fix raid PrioQ scanning wrong raids

- mapadroid/utils/aiohttp/XPathForwardedFor.py
Editing and creating of settings doesn't work when enable_x_forwarded_path_madmin is set if query string is not handled
> Handle query string in XPathForwardedFor

- mapadroid/worker/strategy/AbstractMitmBaseStrategy.py
currentPos and lastPos are geometrical POINT datatype. when represented as WKT this is always lon, lat.  This swaps lat/lon so that it is saved correct in db
Funny enough, there doesn't seem to be anywhere internally in MAD that this db field is actually used. We use the in-memory objects instead.
> trs_status had lat/lon swapped

- mapadroid/db/DbPogoProtoSubmit.py
- mapadroid/utils/questGen.py
Since the quest_item_amount column is a tinyint, it can only store values up to 127, which can't hold the current 700 XP reward (saved rewards were getting truncated to 127).
This PR saves the experience amount in the stardust column, which is a smallint, which can store values up to 32767.
> Store experience in stardust column

- mapadroid/madmin/endpoints/routes/statistics/GetStopQuestStatsEndpoint.py
Doing it in `PokestopHelper.get_with_quests` probably makes more sense, but I don't want to mess there and this is only stats
> Filter quests count by layer in stats

- mapadroid/db/helper/PokestopHelper.py
However no idea why we using POLYGON here not just re-using GeofenceHelper from `fence[1]` and using min/max_lat/lon? Only place calling this with `fence` seems to be stats `statistics/GetStopQuestStatsEndpoint.py`, that already have geofence_helper and we can just do there `stops_in_fence: List[Location] = await PokestopHelper.get_locations_in_fence(self._session, geofence_helper=fence[1]` and that whole POLYGON part is not needed at all? However probably nice to have it in long run?
> Fix Quest Statistics showing all stops count

- static/madmin/templates/events.html
Events are not stored at UTC.
We should respect the timezone during formatting.
> Respect time zone in event list

- static/madmin/templates/status.html
Hide the detailed explanation behind a ?-tooltip on the status-page
> Simplify setting for ✅ in simpler wording
